### ISSUE TITLE
Nested steps

### ISSUE THREAD

**Issue by yannay000** [Shelex/cypress-allure-plugin#10]
**Current behavior:**
When I write cy.allure().step("step_name",true), the new step starts.
All steps go one after another in the report.

**Desired behavior:**
It would be wonderful to have ability to start new step within another step. 
For example:

cy.allure().startStep("parent_step")

- cy.allure().startStep("first_child_step")

- ...

- cy.allure().endStep()

- cy.allure().startStep("second_child_step")

- ...

- cy.allure().endStep()

cy.allure().endStep()

**Comment by Shelex** [comment]
@yannay000 Just released v1.7.0 where such feature is implemented. Moreover, clarified how to create own steps in documentation section: [Cypress commands](https://github.com/Shelex/cypress-allure-plugin#cypress-commands). Could you please check it with your specific case?
