### ISSUE TITLE
videos not getting properly attached in the reports

### ISSUE THREAD

**Issue by bahunov** [Shelex/cypress-allure-plugin#101]
I've noticed when changing allureResultsPath to other than default e.g. "target/allure-results"
then videos (mp4) in the report (allure serve) is not getting attached properly:

![image](https://user-images.githubusercontent.com/22296212/141669973-90bad29d-001e-412b-b1f1-957c608622b6.png)

When looking at result.json, the path seems to be correct:
>"attachments":[{"name":"smoke-specA.js.mp4","type":"video/mp4","source":"../cypress/videos/smoke-specA.js.mp4"}]

Please advice?

**Comment by Shelex** [comment]
Hi @bahunov 
Thank you for reporting.

Yes, as I described in docs, video attachments is quite tricky part in terms of this plugin, as I am attaching video with no info if it will be recorded. So in such case it requires deeper investigation how allure generator treats attachments with relative path.

However, I have found that cypress now provides `after:spec` event which actually gives video path, so now it should be much reliable. In case your cypress version matches rules described in [readme](https://github.com/Shelex/cypress-allure-plugin#update-in-version-2210) it should work fine.

Could you please check v2.21.0 on your end?
