### ISSUE TITLE
Exception in cyCommandStart. Failed to enumerate the properties of 'Storage'.

### ISSUE THREAD

**Issue by Deop** [Shelex/cypress-allure-plugin#102]
**Describe the bug**
Exception in cyCommandStart. Failed to enumerate the properties of 'Storage'.
Issue reproducible from 2.16.1 onwards. Before that there's a 'Converting circular structure to JSON' error (which seems to be fixed in 2.16.1). Issue no longer happen in 2.14.0

**To Reproduce**
Not sure about exact easy steps to reproduce

**Environment (please complete the following information):**
- Cypress version:                                8.7.0
- OS:                                                     Windows

** Developer Tools Console Output **

**Additional context**
When the exception happen I'm starting to work with an iframe so it might something to do with that.

![chrome_2021-11-19_19-57-11](https://user-images.githubusercontent.com/7953144/142675523-d43ae2db-0d04-4082-ae5f-1866c62dcb28.png)

**Comment by Shelex** [comment]
Hi @Deop 
thanks for reporting here.

Should be resolved in v2.20.0, as I have changed that logic a bit to avoid `JSON.stringify` for non-native objects which should solve this case.
Could you please check it on your end? (as I have not reproduced it myself)
