### ISSUE TITLE
All last sub-steps are always in red.

### ISSUE THREAD

**Issue by chip-ext-star** [Shelex/cypress-allure-plugin#107]
**Describe the bug**
All last sub-steps are always in red.

**To Reproduce**
1. set allureLogCypress to false.
2. using allure().logStep().
3. making the test fail.

**Expected behavior**
Only the failed step is in red.

**Environment (please complete the following information):**
- Cypress version:                               9.0
- OS:                                                     Mac 12.0.1

![image](https://user-images.githubusercontent.com/88083969/143840466-b5354fef-d42f-4dbe-8a01-25ebd97f838c.png)
![image](https://user-images.githubusercontent.com/88083969/143840160-fba77a8a-8544-4053-bf8a-6221bd408942.png)

**Comment by Shelex** [comment]
Hi @chip-ext-star 
Thank you for reporting an issue.

Should be resolved in v2.22.1, could you please check it on your end?

**Comment by chip-ext-star** [comment]
Great!!! It's fixed. Thank you.
