### ISSUE TITLE
Soft Assertion support

### ISSUE THREAD

**Issue by chip-ext-star** [Shelex/cypress-allure-plugin#108]
**Is your feature request related to a problem? Please describe.**
I apply the soft assertion concept like this 
![image](https://user-images.githubusercontent.com/88083969/143856035-12ab6a9c-2275-4756-af61-52bcff4a3318.png)

and my test case result looks like this

![image](https://user-images.githubusercontent.com/88083969/143856255-35e052ed-4354-4a6c-ba9d-8e320d772f87.png)

**Describe the solution you'd like**
This is what I expect if I set **allureLogCypress to false**
![image](https://user-images.githubusercontent.com/88083969/143857051-39ab008d-d7c4-44b4-99e1-f9a973c3860c.png)

Can I achieve this on the current version 2.22.1?

**Comment by Shelex** [comment]
@chip-ext-star I don't use soft-assertions so I have no idea how that work in terms of cypress chainer. Is it some kind of plugin or custom implementation?

**Comment by chip-ext-star** [comment]
it works perfectly if the allureLogCypress = true
![image](https://user-images.githubusercontent.com/88083969/143866863-ba9443eb-035e-4d78-b27b-822a97916c08.png)

but when I set allureLogCypress = false, it always fails the last sub-step. I tried this but it doesn't help also
![image](https://user-images.githubusercontent.com/88083969/143867054-57847a3c-8e18-4a68-baa4-4b4804dc6bee.png)

**Comment by Shelex** [comment]
@chip-ext-star Anyway I cannot reproduce it as I don't use soft assertions at all.
Is it some plugin or some implementation that I can use to reproduce?

**Comment by chip-ext-star** [comment]
@Shelex any good news :)

**Comment by Shelex** [comment]
> @Shelex any good news :)

Hi @chip-ext-star. Actually none. It requires debugging some custom code behaviour, moreover the flow of cypress events and how they are reflected in allure. I am not a big fan of disabling that logging to be honest, as reports are for debugging purpose, nobody else read that steps.
So time/value ratio is not so high for me to throw away everything and start looking at this issue. So apologies, but I will check it when have a bit more free time.

**Comment by chip-ext-star** [comment]
Thank you @Shelex

**Comment by Shelex** [comment]
Hi @chip-ext-star, now I have an update!

To start with, code from your sample
```js
cy.allure().logStep('1');
chai.softExpect(true).to.be.eq(false);
cy.allure().logStep('2');
chai.softExpect(true).to.be.eq(true);
```
is not working fine, because here we have mixed cypress chainable (async) and chai.softExpect (sync). You can check it in interactive mode (cypress open) and see that test duration counter will not stop, which means that control flow is broken, so I would be super careful using such thing as soft assertions ( moreover it may lead to poor test design or act as a mark that everything is done via UI and a lot of things are tested in terms of single test, however that is separate story).

If this warning still not frightened you 😃, there are two options:
- synchronous version of allure api
```js
const allure = Cypress.Allure.reporter.getInterface();
allure.step('1');
chai.softExpect(1).to.be.eq(2);
allure.step('2');
chai.softExpect(3).to.be.eq(3);
```
 - asynchronous version
```js
cy.allure()
   .logStep('1')
   .then(() => {
      chai.softExpect(1).to.be.eq(2);
   });

cy.allure()
   .logStep('2')
   .then(() => {
      chai.softExpect(3).to.be.eq(3);
   });
```
As only place where information that assertion is failed is the command log, I have published `v2.23.0`, where added the listener for 'log:added' event, and if some log is failed, then current runnable (step, parent step, hook, etc.) status will change to failed. Hope that solves this issue.

**Comment by chip-ext-star** [comment]
hi @Shelex,

I updated to `v2.23.0` and used the asynchronous version. But it says `Property 'then' does not exist on type 'Allure'.ts(2339)`

<img width="466" alt="image" src="https://user-images.githubusercontent.com/88083969/151496185-2fb6a2e0-d2ae-483d-8bf7-246497d1ceeb.png">

Could you pls help?

**Comment by Shelex** [comment]
> hi @Shelex,
> 
> I updated to `v2.23.0` and used the asynchronous version. But it says `Property 'then' does not exist on type 'Allure'.ts(2339)`
> 
> <img width="466" alt="image" src="https://user-images.githubusercontent.com/88083969/151496185-2fb6a2e0-d2ae-483d-8bf7-246497d1ceeb.png">
> 
> Could you pls help?
> 

Hi.
Have you included allure plugin types to your tsconfig, as mentioned in readme?

**Comment by chip-ext-star** [comment]
when I put these includes in tsconfig, all my ts files are corrupted.
`"include": [
    "../node_modules/@shelex/cypress-allure-plugin/reporter",
    "../node_modules/cypress",
   ]`

<img width="544" alt="image" src="https://user-images.githubusercontent.com/88083969/151525417-fc113c1c-8953-4617-8e44-21dcf7fae59d.png">

**Comment by Shelex** [comment]
So the problem is not with functionality, but vscode configuration (tscofig).
