### ISSUE TITLE
There are no results in report when before hook fails and next block is describe() not it()

### ISSUE THREAD

**Issue by romankhomitskyi** [Shelex/cypress-allure-plugin#113]
**Describe the bug**
The following code cause the issue 

```
describe('one', () => {
	before(() => {
		expect(true).to.equal(false); // when before hook fails and the next block is describe
	});

	describe('second', () => {
		before(() => {
			expect(true).to.equal(true);
			cy.log('gg');
		});
		it('should log 2', () => {
			cy.log('log 2');
		});
	});
});
```

There is only container.json file in allure-results and no attachments 

However when before hooks fails and the next block is it()  it just works fine

```
describe('one', () => {
	before(() => {
		expect(true).to.equal(true); // pass
	});

	describe('second', () => {
		before(() => {
			expect(true).to.equal(false); // fails but there are results in report
			cy.log('gg');
		});
		it('should log 2', () => {
			cy.log('log 2');
		});
	});
});
```
Now allure-results folder contains  result.json, container.json and attachments

**Environment (please complete the following information):**
- Cypress version:                                8.6.0
- cypress allure plugin:                         2.23.0

**Comment by Shelex** [comment]
Hi @romankhomitskyi 
Thank you for posting an issue.

Technically it sounds valid - you have some hook failing, but there is no test it is attached to, so you get just failed suite.
It requires more investigation as I have not seen such cases of using nested `describe` blocks before and don't even understand the purpose of such test structure.

**Comment by romankhomitskyi** [comment]
> Hi @romankhomitskyi Thank you for posting an issue.
> 
> Technically it sounds valid - you have some hook failing, but there is no test it is attached to, so you get just failed suite. It requires more investigation as I have not seen such cases of using nested `describe` blocks before and don't even understand the purpose of such test structure.

The purpose is to create independent it() blocks or describe suites so that when I add describe.only() to one of the suites it will  successfully because of before() ( or beforeSuite hook so to say)

First describe is feature under test
Nested describes are scenarios 
for example first nested describe is for admin
second nested describe is for user

So we have well structured spec also worth mention that such structure looks good in report

**Comment by Shelex** [comment]
> Nested describes are scenarios

That is quite common anti-pattern against mocha syntax design. `describe` block is a test suite (already) - an abstraction to structure your tests, not a scenario. Moreover if you consider `it` as a test step - that is completely wrong. If you need unique pre-condition for each test it makes sense to make it as a part of test instead of fighting cypress, mocha and plugins.

The solution is to structure your features with folders and have one suite per file instead of massive nesting. 
Example for feature `signUp`: you may have folder `signup` with files `signup/user.spec.js` and `signup/admin.spec.js`, or just `signup.spec.js` but with 2 separate suites - for user and admin. 

As for the reporter, Allure supports 3 level structure:
`parentSuite` -> `suite` -> `subSuite`, which may be configured with labels, but this plugin is exposing commands for them.
For example, on my projects I am adding folder name as `parentSuite` in global beforeEach hook (in commands.js):
```js
const path = require('path');
...
beforeEach(() => {
    const { spec } = Cypress;
    const folderName = path.dirname(spec.name);
    cy.allure()
        .label('parentSuite', folderName)
        .testParameter('spec', spec.name);
});
```

**Comment by romankhomitskyi** [comment]
> > Nested describes are scenarios
> 
> That is quite common anti-pattern against mocha syntax design. `describe` block is a test suite (already) - an abstraction to structure your tests, not a scenario. Moreover if you consider `it` as a test step - that is completely wrong. If you need unique pre-condition for each test it makes sense to make it as a part of test instead of fighting cypress, mocha and plugins.
> 
> The solution is to structure your features with folders and have one suite per file instead of massive nesting. Example for feature `signUp`: you may have folder `signup` with files `signup/user.spec.js` and `signup/admin.spec.js`, or just `signup.spec.js` but with 2 separate suites - for user and admin.
> 
> As for the reporter, Allure supports 3 level structure: `parentSuite` -> `suite` -> `subSuite`, which may be configured with labels, but this plugin is exposing commands for them. For example, on my projects I am adding folder name as `parentSuite` in global beforeEach hook (in commands.js):
> 
> ```js
> const path = require('path');
> ...
> beforeEach(() => {
>     const { spec } = Cypress;
>     const folderName = path.dirname(spec.name);
>     cy.allure()
>         .label('parentSuite', folderName)
>         .testParameter('spec', spec.name);
> });
> ```

Please don't misunderstand me, but I was designing my tests according to these [best practices ](https://github.com/goldbergyoni/javascript-testing-best-practices#clap-doing-it-right-example-structuring-suite-with-the-name-of-unit-under-test-and-scenarios-will-lead-to-the-convenient-report-that-is-shown-below)

Also by nested describes I meant the following scenario

```
describe('Decreasing rent', () => {
	// const rent = 100
	before(() => {
		// create admin and user
		// create rent with value 100$ and share with user
		// login as user an accept rent
		// login as admin and decrease rent to 50
	});

	describe('Check rent on admin side', () => {
		it('rent should have value 50 ', () => {});

		// and more checkers
	});
	describe('Check rent on user side', () => {
		it('rent should have value 50 ', () => {});

		// and more checkers
	});
});

```

I would like to have these structure instead of splitting these describes into two specs 

Also my it() is not represent a step, it's more an assertion, steps are mostly in before hooks or in it() itself

**Comment by Shelex** [comment]
> I would like to have these structure instead of splitting these describes into two specs

However that is exactly the core recommendation for designing tests - isolation. Here you have admin and user functionality combined together. But it would be much easy to maintain, read and support when separated:

```js
describe('User rent', () => {
    before(() => {
        // actions done via backend
        // create admin and user
    });

    beforeEach(() => {
        // create rent with value 100$ and share with user
        // login as user an accept rent
    });

    afterEach(() => {
        // remove rent
    });

    after(() => {
        // delete user
        // delete admin
    });

    it('should be able to display actual rent value', () => {
        expect(rent).to.be.eq(100);
    });

    it('should be able to display decreased rent value', () => {
        // via admin api decrease rent to 20
        expect(rent).to.be.eq(20);
    });

    it('should be able to display increased rent value', () => {
        // via admin api increase rent to 50
        expect(rent).to.be.eq(50);
    });
});

describe('Admin rent', () => {
    before(() => {
        // create admin
    });

    beforeEach(() => {
        // create rent with value 100
    });

    afterEach(() => {
        // remove rent
    });

    after(() => {
        // delete admin
    });

    it('should contain initial rent value', () => {
        expect(rent).to.be.eq(100);
    });

    it('should be able to decrease rent value', () => {
        // decrease rent to 20
        expect(rent).to.be.eq(20);
    });

    it('should be able to increase rent value', () => {
        // increase rent to 50
        expect(rent).to.be.eq(50);
    });
});
```

**Comment by Shelex** [comment]
Hi @romankhomitskyi 
Have released v2.25.0 where it should be handled now.
Could you please check it on your side also?

**Comment by romankhomitskyi** [comment]
I run test with the following code

```
describe('one', () => {
	before(() => {
		expect(true).to.equal(false); // when before hook fails and the next block is describe
	});

	describe('second', () => {
		before(() => {
			expect(true).to.equal(true);
			cy.log('gg');
		});
		it('should log 2', () => {
			cy.log('log 2');
		});
	});
});
```

And when before fails and there is the following code in plugins/index.ts
	config.env = process.env;
	allureWriter(on, config);
	
There is no results in report at all

However when I remove	config.env = process.env; and run test again with failing before hook it shows the report properly

**Comment by Shelex** [comment]
> config.env = process.env;

Because you override cypress config with data from process.env it may not function properly. 
Moreover, I absolutely have no idea why it is needed as there are packages like `dotenv` and you can add `CYPRESS_` prefix to your env variables and they will be added to config.env automatically.

**Comment by romankhomitskyi** [comment]
> > config.env = process.env;
> 
> @romankhomitskyi Because you override cypress config env with data from process.env so it may not function properly (for example missing env.allure or env.allureResultsPath which are used by plugin). Moreover, I absolutely have no idea why it is needed as there are packages like `dotenv` and you can add `CYPRESS_` prefix to your env variables and they will be added to config.env automatically.

I thought it was fixed in  [this issue](https://github.com/Shelex/cypress-allure-plugin/issues/110) 
In addition, it looks like code like this
` config.env = process.env;`
Merge/Add properties rather override them

**Comment by romankhomitskyi** [comment]
I was wondering if there is a chance to print failed method/function name in logs when global before fails? 
like `Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: Suite one at UserPage.viewUserProfile`

**Comment by Shelex** [comment]
> > > config.env = process.env;
> > 
> > 
> > @romankhomitskyi Because you override cypress config env with data from process.env so it may not function properly (for example missing env.allure or env.allureResultsPath which are used by plugin). Moreover, I absolutely have no idea why it is needed as there are packages like `dotenv` and you can add `CYPRESS_` prefix to your env variables and they will be added to config.env automatically.
> 
> I thought it was fixed in [this issue](https://github.com/Shelex/cypress-allure-plugin/issues/110) In addition, it looks like code like this ` config.env = process.env;` Merge/Add properties rather override them

In javascript when you assign to variable, which already has one object, some other object - it just replace it, no merge or properties addition is happening.

**Comment by Shelex** [comment]
> I was wondering if there is a chance to print failed method/function name in logs when global before fails? like `Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: Suite one at UserPage.viewUserProfile`

I guess the proper place for it is another issue for enhancement where I would suggest discussing this feature rather than mixing up this thread.

**Comment by romankhomitskyi** [comment]
Ok, thanks fo replies and fix!!
