### ISSUE TITLE
Title for before hook steps section is unknown 

### ISSUE THREAD

**Issue by olikbarabolik** [Shelex/cypress-allure-plugin#117]
**Describe the bug**

Section for before hook is unknown

**To Reproduce**

Run script:
describe('Отчет', () => {
    before(() => {
        cy.allure().step('Шаг внутри before')
    })
})

**Expected behavior**
Section for before hook has correct title

**Environment (please complete the following information):**
•	Cypress version: 8.7.0
•	Allure plugin version 2.23

![image](https://user-images.githubusercontent.com/62029315/150957353-f407baf8-c2e7-48f2-aabf-431a9e999176.png)

**Comment by Shelex** [comment]
Hi @olikbarabolik 
Could you please suggest what allure reporter version do you use? As this UI is quite weird.

**Comment by Shelex** [comment]
Hi, @olikbarabolik 
Unfortunately I am not able to reproduce it as Allure report giving me proper results for this test code:

```js
describe('Отчет', () => {
    before(() => {
        cy.allure().logStep('шаг внутри before');
    });

    it('test', () => {
        cy.wrap(true).should('be.eq', true);
    });
});
```

<img width="922" alt="Allure Report 2022-01-28 19-13-05" src="https://user-images.githubusercontent.com/11396724/151591695-38d4e53f-4496-4110-b59b-dd6db466bf32.png">

**Comment by olikbarabolik** [comment]
@Shelex version 2.17.2
![image](https://user-images.githubusercontent.com/62029315/151984780-3eeaaece-be5a-4886-ae7e-8ab534b29506.png)

**Comment by Shelex** [comment]
Hi @olikbarabolik 
So as I see report is quite fine, steps from before section are displayed. Could you please clarify what is the problem or it is resolved?

**Comment by kamiloski88** [comment]
Hi, I want to use Steps to my tests, but after write
 it('should not allow to change a passport type', function () {
    cy.allure().step("Login")
   cy.login()
})

on cy.allure i get in my ide "Property 'allure' does not exist on type 'cy & EventEmitter'". 
what should I do?

**Comment by Shelex** [comment]
> Hi, I want to use Steps to my tests, but after write it('should not allow to change a passport type', function () { cy.allure().step("Login") cy.login() })
> 
> on cy.allure i get in my ide "Property 'allure' does not exist on type 'cy & EventEmitter'". what should I do?

Please check if you have included types in your tsconfig.
