### ISSUE TITLE
Do not attach screenshots and add separate section 'Screenshots" to report

### ISSUE THREAD

**Issue by kamiloski88** [Shelex/cypress-allure-plugin#119]
Im using visual regression tests - i have folders Actual - with actual run screenshots, Base - base screenshots and diffs - folder with diff between Actual and Base. I have node script which attaches those screenshots to report. But now when Im running tests and attaching my screenshots from visual regressions I dont need one that is attached by this plugi. Can I turn off automatic attaching screenshots from plugin? 
And snd question, is the way to add do generated report separates section, eg Screenshots where will be palced screenshots? like this
![image](https://user-images.githubusercontent.com/17034737/152002385-7cd0e249-fe7f-4323-9469-b20f65da7b5d.png)

**Comment by Shelex** [comment]
Hi @kamiloski88 
Thank you for opening an issue.

> Can I turn off automatic attaching screenshots from plugin?

You mean all screenshots\attachments or just that screenshots that are used for diffs? What is the point of adding them via script? Maybe we can improve screenshot attachments to work the same way as you have with script?

> is the way to add do generated report separates section

I guess it is possible by extending Allure with [custom plugin](https://docs.qameta.io/allure/#_allure_plugins_system), but that could be done separately from this plugin.

**Comment by kamiloski88** [comment]
Thanks for fast reply. To clarify I'm using "cypress-visual-regression" and "cypress-image-snapshot". and retries.
`You mean all screenshots\attachments or just that screenshots that are used for diffs? What is the point of adding them via script? Maybe we can improve screenshot attachments to work the same way as you have with script?`
On this point I would like to disable attaching screenshots by yours plugin. There is multiple reasons:
1. Screenshots are duplicated - the same screenshot is in allure-results folder and in my Actual folder
2. I use my scrpit to attach all screenshots (base + actual + diff) to report if tests fail. Probably it's your script but modified by me (you send it to me on gitter.im - in pm about 2years ago :) ) 

Maybe it will be some solution to indicate the paths to base + actual + diff and connect them with failed test.
But now I wolud like to just not attach this screenshot from allure-results

`I guess it is possible by extending Allure with custom plugin, but that could be done separately from this plugin.`
can you give me a hint how to?

**Comment by Shelex** [comment]
> Probably it's your script but modified by me (you send it to me on gitter.im - in pm about 2years ago :) )

That is exactly a purpose of this plugin - to replace such scripts :D

> Screenshots are duplicated - the same screenshot is in allure-results folder and in my Actual folder

Yes, because to make it safe I copy all screenshots in allure-results to have them in allure-report after generation, instead of using relative paths which caused issues previously

> Maybe it will be some solution to indicate the paths to base + actual + diff and connect them with failed test.

Of course, here is the [example](https://github.com/Shelex/cypress-allure-snapshots-example/blob/master/cypress/support/index.js#L12) for `cypress-plugin-snapshots`. For other image-diff plugins idea is quite same. 

> I would like to disable attaching screenshots by yours plugin

Ok, will check it, however maybe I would start with removing screenshot duplicates in case they are used in diffs.

> can you give me a hint how to?

Unfortunately, no. Never used that before.

**Comment by kamiloski88** [comment]
`That is exactly a purpose of this plugin - to replace such scripts :D`
Yeah, I understand but generating report in this way does not meet my expectations.
`Of course, here is the example for cypress-plugin-snapshots. For other image-diff plugins, idea is quite same.`
Thanks, will check it
`Ok, will check it, however maybe I would start with removing screenshot duplicates in case they are used in diffs.`
Maybe just add option to do not copy and attach screenshot:)

btw, thanks for quick reply and help 👍

**Comment by kamiloski88** [comment]
BTW. i checked it https://shelex.github.io/cypress-allure-snapshots-example/allure-report/index.html#suites/4b95d465683b069ecbb7625b462ca33f/66efc39f2bd7671b/ and I like this plugin :) maybe I will try to use it:)

**Comment by Shelex** [comment]
> BTW. i checked it https://shelex.github.io/cypress-allure-snapshots-example/allure-report/index.html#suites/4b95d465683b069ecbb7625b462ca33f/66efc39f2bd7671b/ and I like this plugin :) maybe I will try to use it:)

If you mean that `cypress-plugin-snapshots` - use at your own risk, I have no idea if it is working properly :D

Btw, in v2.26.0 there is config `allureSkipAutomaticScreenshots` which could be enabled and then screenshots will not be attached by plugin.

**Comment by kamiloski88** [comment]
One more thing, how to achieve this result? This section with screenshot divs + those radio buttons. I have installed this plugin in my project, snapshot are properly saved in __image_snapshots__ (base diff actual) but I dont havve in my report this section from screenshots - Screenshots in my case are attached in Test body at the bottom
![image](https://user-images.githubusercontent.com/17034737/152170973-a91c7693-da2c-4bf7-b8cf-574fc04fc67b.png)

**Comment by Shelex** [comment]
@kamiloski88 because you have to add that code in afterEach hook to let Allure know that it should group them in one component. That is the purpose of `cy.allure().label('testType', 'screenshotDiff')`

**Comment by kamiloski88** [comment]
yes, I know I use your code from support/index.js but its not working

**Comment by kamiloski88** [comment]
@Shelex ok, I have no idea, still cannot add it do results. Im using NPM, instead of yarn, can it make difference? I run testo on windows and on docker image and the result is the same. When I run your example it works properly.

**Comment by Shelex** [comment]
@kamiloski88 yep, found issue, published a fix as v2.26.1

**Comment by kamiloski88** [comment]
@Shelex great, thanks now it works! :)
