### ISSUE TITLE
Link with multiple features

### ISSUE THREAD

**Issue by xescuder** [Shelex/cypress-allure-plugin#121]
We want to trace the test with more than one feature/epic/story.

Besides we can enter in discussion about if it is semantically correct, we're using in it already with other frameworks like JUnit 5, but we've tried with cypress-allure-plugin and it doesn't allow us to do it.

Can you add this capability? 

Thanks in advance.

**Comment by Shelex** [comment]
@xescuder duplicated labels for epic, feature and story should be allowed in v2.26.2

**Comment by xescuder** [comment]
Great! Thanks!
