### ISSUE TITLE
Allure report not picking up on skipped tests due to before/ beforeEach failure 

### ISSUE THREAD

**Issue by pmweeks98** [Shelex/cypress-allure-plugin#122]
**Describe the bug**
If cypress has a failure in the before or beforeEach hook the remaining tests are skipped. These skips are not being picked up in the report

**To Reproduce**
```
    describe('testSuite', () => {
        before(() => {
           expect(true).to.eq(false);
        }
        it('test name', () => {
            <test content>
        });
    });
```
The before fails and the test is skipped
The report contains the before failure but not the tests skipped

**Expected behavior**
Allure report contains failure of before and reports on the number of tests skipped

**Environment (please complete the following information):**
- Cypress version:                                7..7
- OS:                                                     Linux (RHEL 8):
- Plugin Version                                    2.18.0

**Comment by Shelex** [comment]
Hi @pmweeks98 
Could you please upgrade plugin to latest version? As far as I remember something similar was already adressed.

**Comment by pmweeks98** [comment]
@Shelex 
Updated to 2.26.2 and now skipped tests are being reported as broken. 
Is this the correct designation for skipped tests due to beforeEach failure?

**Comment by Shelex** [comment]
> @Shelex Updated to 2.26.2 and now skipped tests are being reported as broken. Is this the correct designation for skipped tests due to beforeEach failure?

Yes, beforeEach is not a test itself, it is a precondition, so in case it fails - that may influence other tests, as a result they are intentionally marked as broken.

**Comment by pmweeks98** [comment]
Ah grand thank you, that solves the problem so
