### ISSUE TITLE
Retry failed test and screenshot diff - test passing when should fail

### ISSUE THREAD

**Issue by kamiloski88** [Shelex/cypress-allure-plugin#123]
**Describe the bug**
I run test with image diff (cypress-plugin-snapshots) if i run it with retry (test should fail - base screenshot is not proper for simulation), test should fail for each run, but at the end I get message that all tests passed after generate allure report I can see that test is Passed but screenshots with diffs are attached (difs exist). When I set retry to 0 (do not retry failed tests) then the same test is failing.

**Expected behavior**
If test is failed for each test run (retry) then test should have status failed
![image](https://user-images.githubusercontent.com/17034737/152773636-5fc2ca37-9b3c-4b6a-aaa9-e158d3f22ae0.png)

**Comment by Shelex** [comment]
Hi @kamiloski88 
In case that is the information plugin receives from cypress (test is passed) - the problem is not related to plugin.
I would recommend go to `cypress-plugin-snapshots` repo to clarify that behaviour.
