### ISSUE TITLE
Persist allure data between different origin hosts

### ISSUE THREAD

**Issue by Shelex** [Shelex/cypress-allure-plugin#125]
**Describe the bug**
In case test contains redirects or opening pages from different origins Cypress loads index.js file again wiping allure data.
Could result in missing test data or with latest allure-plugin version you will see such tests as skipped.
Caused by https://github.com/cypress-io/cypress/issues/20050

**To Reproduce**
Just visit different domains in same test with disabled chromeWebSecurity.
Use event listener breakpoints for "beforeunload" to track in console that `Cypress.Allure.reporter.runtime.writer` is flushed after new origin.

**Expected behavior**
State should be persisted

**Comment by AjayLohika** [comment]
Hello @Shelex , 
Any fix is available for this issue?. Seems its pending for long?.

**Comment by Shelex** [comment]
No fix available from plugin side.
There is a chance that it will be self-healed in case you will use [cy.origin](https://docs.cypress.io/api/commands/origin) available in Cypress v9.6.0 to handle multiple domains.
However I have not checked that yet.

**Comment by Shelex** [comment]
Could not reproduce this issue again with cypress v10+, so I assume it was resolved by changes in Cypress multi-domain handling.
