### ISSUE TITLE
Question: How to add TMS link for Scenario Outline - We have created testcases for each examples

### ISSUE THREAD

**Issue by DeChrish** [Shelex/cypress-allure-plugin#126]
**Is your feature request related to a problem? Please describe.**
TMS- One to one mapping between test script and test cases created. Currently we need to create multiple examples block to add unique TMS id

**Describe the solution you'd like**
Do we have any object available to add the testcase id vi code only for Scenario Outline

**Additional context**

**Comment by Shelex** [comment]
Hi @DeChrish 
I guess [gherkin and tms or issue links](https://github.com/Shelex/cypress-allure-plugin#gherkin-and-tms-or-issue-links) section in README may help your case.
You can add just additional column with name `tms` and it will be converted to link with tms id for specific example test.
