### ISSUE TITLE
Allure report shows a failed test for a test that passed

### ISSUE THREAD

**Issue by willischu** [Shelex/cypress-allure-plugin#128]
**Describe the bug**
We have a Cypress test that is passing on CI (there was no retry either) but is showing as a failed test on the Allure report.
- Test that is failing on the Allure report but is passing on CI:
![image](https://user-images.githubusercontent.com/10055168/154756249-d8cce063-0902-4eb5-9d39-4b540f785f21.png)
![image](https://user-images.githubusercontent.com/10055168/154756765-0a9f3c5c-5325-49e6-b7e2-b8f00c97f811.png)

- What it looks on the Allure report
![image](h
<img width="500" alt="Screen Shot 2022-02-18 at 3 29 52 PM" src="https://user-images.githubusercontent.com/10055168/154757099-e4227247-eac9-4f2b-86a8-b47c97690b1a.png">

**To Reproduce**
- Hard to reproduce as this seems like an edge case with our tests
1. Run a suite of tests on CI
2. The same test continues failing on the Allure report but actually passed on CI

**Expected behavior**
- Allure report should show 0 failures when CI is showing 0 failures for Cypress tests

**Environment (please complete the following information):**
- Cypress version:                                9.5.0
- OS:                                                      Mac

** Developer Tools Console Output **

**Additional context**

**Comment by Shelex** [comment]
Hi @willischu 
Have not seen such issue. I see that allure fails because of "GET" step, if there is some network request, could you please enable in cypress.json env variable "allureAttachRequests" by setting "true" in order to check that api call is fine?

**Comment by willischu** [comment]
Thank you - will look into that. The test that is showing up as a failure on Allure but passing on Cypress actually fails first --> retries --> passes. And because the video artifact for the passed test gets deleted, it reports the first failed test run before it retried and passed.

**Comment by Shelex** [comment]
While working on v2.30.0 I have checked this case too, and cannot reproduce it for now. Current assumption is it was related to hooks handling logic.
So please check it for your case and feel free to reopen if you can still reproduce it.
