### ISSUE TITLE
How to get the test case count, pass count and fail count from allure report ?

### ISSUE THREAD

**Issue by karthikeyanalaguraja** [Shelex/cypress-allure-plugin#129]
I am using cypress and gitlab. We integrated the allure-* folders to AWS s3 and those will be a static website. Now i need to find out the no of test cases executed, test cases passed and test cases failed.

Is there a property for allure to get this information?

**Comment by Shelex** [comment]
Hi @karthikeyanalaguraja .

As far as I know - there is no API to get that from report.
However, all data that report uses is inside `/data/suites.json` [example](https://shelex.github.io/cypress-allure-plugin-example/allure-report/data/suites.json) which contain executed suites, tests and statuses, so maybe you can use it for calculating results.
