### ISSUE TITLE
Can't set description using cy.allure().descriptionHtml() from support/index.ts afterEach

### ISSUE THREAD

**Issue by khollenbeck3** [Shelex/cypress-allure-plugin#130]
**Describe the bug**
Calling `cy.allure().descriptionHtml('<h1>Test Description</h1>')` from a global afterEach defined in the support/index.ts has no effect on the allure report (no error is thrown but no description gets set)

**To Reproduce**
1. Add `cy.allure().descriptionHtml('<h1>Test Description</h1>')` to an afterEach defined in support/index.ts
2. Run a cypress test and generate allure report
3. See missing description in allure report

**Expected behavior**
Description should show a heading of **Test Description**

**Environment (please complete the following information):**
- Cypress version:                                9.00
- OS:                                                     Mac

**Additional context**
Not sure if this is actually expected behavior or not. We were hoping to set `cy.allure().descriptionHtml()` in a global afterEach similar to how we set `cy.allure().parentSuite()` in a global beforeEach, but it's seeming now like there may not be a way to set description outside of the actual `it` of the test. Would you be able to confirm whether setting descriptionHtml should be possible in a before or after hook? Thanks!

**Comment by Shelex** [comment]
Hi. 
I can confirm it is writing descriptionHtml to `afterEach` step inside test, however, it should be just test itself, because these descriptions are not visible for steps.
Have published a fix in v2.30.1 where description will be explicitly attached to test only.
