### ISSUE TITLE
windows encoding on linux jenkins 

### ISSUE THREAD

**Issue by lukasstachBSC** [Shelex/cypress-allure-plugin#132]
**Describe the bug**
I ran cypress tests, generated allure report and i wanted to send it to MS TEAMS via https://github.com/maritome/cypress-msteams-reporter. but it failed on \r issue in some file. so i downloaded entire allure-report and I found that allure-report\plugins\behaviors\index.js and allure-report\plugins\packages\index.js are encoded as CRLF, all other files are LF

**To Reproduce**
1. install https://github.com/maritome/cypress-msteams-reporter
2. install cypress allure plugin
3. run cypress tests
4. generate report
5. run ms teams reporter

**Expected behavior**
ms teams reporter should send message to MS TEAMS - i tried it on windows PC and there was no issue

**Environment (please complete the following information):**
- Cypress version:                                9.51
- OS:                                                    Linux (distro):

** Developer Tools Console Output **
<---------------------------------------------
+ yarn allure generate
yarn run v1.22.5
$ /data/jenkins/workspace/xxx/node_modules/.bin/allure generate
Report successfully generated to allure-report
Done in 1.86s.
+ rm -rf allure-results
+ mv allure-report dist/cypress/apps/gib-e2e/allure-report/
Archiving artifacts
Recording fingerprints
+ yarn cypress-msteams-reporter --report-path dist/cypress/apps/gib-e2e/allure-report/widgets/status-chart.json --testEnv-path dist/cypress/apps/gib-e2e/allure-report/widgets/environment.json
yarn run v1.22.5
$ /data/jenkins/workspace/xxx/node_modules/.bin/cypress-msteams-reporter --report-path dist/cypress/apps/gib-e2e/allure-report/widgets/status-chart.json --testEnv-path dist/cypress/apps/gib-e2e/allure-report/widgets/environment.json
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
script returned exit code 127
--------------------------------------------->

**Additional context**

**Comment by monkpit** [comment]
Seems this is an issue with the `cypress-msteams-reporter` - reported on their github here: https://github.com/maritome/cypress-msteams-reporter/issues/5

**Comment by lukasstachBSC** [comment]
yes yes, i already commented there, and i forgot to close this issue :)

**Comment by Shelex** [comment]
Closing, as it seems issue is not relevant to this package.
