### ISSUE TITLE
Sorry cypress and parallel run tests

### ISSUE THREAD

**Issue by kamiloski88** [Shelex/cypress-allure-plugin#133]
I'm using this plugin with sorry cypress to parallel them, when I run multiple test runs
yarn cy2 run --browser chrome --headless --record --key XXX --parallel --ci-build-id xcvsc
yarn cy2 run --browser chrome --headless --record --key XXX --parallel --ci-build-id xcvsc
yarn cy2 run --browser chrome --headless --record --key XXX --parallel --ci-build-id xcvsc

I get an error in Teamcity build log:
Your pluginsFile threw an error from: /opt/buildagent/work/530b148f57a4a8e6/cypress/plugins/index.js
[35m [39m
Error: listen EADDRINUSE: address already in use 127.0.0.1:2121
at Server.setupListenHandle [as _listen2] (node:net:1315:16)
at listenInCluster (node:net:1363:12)
at GetAddrInfoReqWrap.doListen (node:net:1501:7)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8)
We stopped running your tests because a plugin crashed.

**Comment by Shelex** [comment]
I am not sure how this plugin may cause such issues as it does not use any ports.
This is quite a common error if you do not containerise your cypress instances as they may fight for same machine resources.

I have found similar issue: https://github.com/meinaart/cypress-plugin-snapshots/issues/76 
But `cypress-plugin-snapshots` USES server with some port internally, which is not a case with this plugin.

So please check your registered plugins.
