### ISSUE TITLE
Failure in beforeEach halfway during test reports passed tests as skipped

### ISSUE THREAD

**Issue by pmweeks98** [Shelex/cypress-allure-plugin#134]
**Describe the bug**
When a beforeEach fails during a suite the remaining tests are skipped. However the allure report says all but the first test have been skipped, even though some had passed

**To Reproduce**
1. Have beforeEach fail during a test in the middle of your suite
2. View allure report

**Expected behavior**
Passed tests report as passed, skipped as skipped

**Environment (please complete the following information):**
- Cypress version:                                7.7.0
- Allure plugin version:                         2.26.2

**Screenshots**
From video recording
![Screenshot from 2022-03-23 10-21-14](https://user-images.githubusercontent.com/56260662/159678069-5a6404c8-04d2-42e9-b0dc-a50396ded161.png)
Allure report
![Screenshot from 2022-03-23 10-23-30](https://user-images.githubusercontent.com/56260662/159678321-03178c42-c5e8-452b-9ed9-94a55bfb3218.png)

**Comment by Shelex** [comment]
Fix published in v2.30.0.
Please reopen in case you can still reproduce it.
