### ISSUE TITLE
Failed beforeEach hook missing attached request logs

### ISSUE THREAD

**Issue by Shelex** [Shelex/cypress-allure-plugin#135]
**Describe the bug**
Failed beforeEach hook missing attached request logs

**To Reproduce**
1. Use beforeEach hook with some http request
2. make it fail

**Expected behavior**
Request info is attached to report

**Environment (please complete the following information):**
- Cypress version:                               ^7.4.0
- OS:                                                     Mac

**Additional context**
Request is failing with server error.

**Comment by kunalashar25** [comment]
**Slight Correction to the steps:**
1. Add before hook in `cypress/support/index.js` with some HTTP request
2. Add beforeEach hook with some HTTP request in `*.spec.ts`
3. Make beforeEach hook fail.

**Actual Result:**
- Report shows Request/Response info of requests from before hook
- It **does not** display data from beforeEach hook when failed

**Expected Result:**
- Request/Response info of beforeEach hook should be displayed in the report.

**Comment by Shelex** [comment]
Fix published in v2.30.0. Now attachments should be handled properly.
Please reopen in case you can still reproduce it.
