### ISSUE TITLE
Add opportunity to add video to allure report

### ISSUE THREAD

**Issue by Xaosik** [Shelex/cypress-allure-plugin#14]
Hi there, I've tried to add videos to allure report, but with no success
I've tried to rename PNG format to WEBM in AllureInterface and writer files, it writes video and attached to report, but it record seconds after test fails, like a screenshot 

Even add video to report as cypress does would be perfect. Cypress attaches full video to each test suite even it passes

Many thanks!

**Comment by Shelex** [comment]
@Xaosik 
just published v1.8.0 where cypress video attachment have been added.
Also, there are some nuances right now, so I have added that points of concern into documentation: https://github.com/Shelex/cypress-allure-plugin#screenshots-and-videos

**Comment by Xaosik** [comment]
It works perfectly, Thanks a bunch!

**Comment by crisreekoh** [comment]
How to attach screenshot in passed test? thanks

**Comment by Xaosik** [comment]
> How to attach screenshot in passed test? thanks

Hi, try to change default configuration screenshotOnRunFailure, that described in cypress docs
