### ISSUE TITLE
Snapshots made by cypress-plugin-snapshots are not included in the report

### ISSUE THREAD

**Issue by kirill-konshin** [Shelex/cypress-allure-plugin#15]
**Describe the bug**

Looks like there's missing integration between Allure plugin and Snapshot plugin:

**To Reproduce**

```js
cy.document().toMatchImageSnapshot();
```

**Expected behavior**

Should result in snapshot added to report, but it does not. Especially when snapshot does not match.

**Environment (please complete the following information):**
- Cypress version:                                4.10.0
- OS:                                                    Mac

**Comment by Shelex** [comment]
@kirill-konshin Thank you for reporting an issue.
Seems like a feature request to have output from other plugins.
But basically that is what Allure API designed for - to extend reporting with specific info from your framework you add information with parameters or attachments as there may be corner cases with various data formats or circular structures, so it is on user side to define expected behaviour and specifics of usage.
Also, there are a lot of "snapshot" plugins for Cypress, could you please clarify which one you are using, so I could check?

**Comment by Shelex** [comment]
@kirill-konshin 
Here you can find the example how to add image attachments to report: [cypress-allure-snapshots-example](https://github.com/Shelex/cypress-allure-snapshots-example).
[Report](https://shelex.github.io/cypress-allure-snapshots-example/allure-report/index.html#suites/4b95d465683b069ecbb7625b462ca33f/818da8f046b96dc6/) and [Readme](https://github.com/Shelex/cypress-allure-snapshots-example#description) with some additional information is also available.

Hope it will help.

**Comment by talmai-dorel** [comment]
@Shelex i cloned "cypress-allure-snapshots-example" and it very useful thanks! how do you do that the electron browser that running on the screen will be always on 100%
![image](https://user-images.githubusercontent.com/70937586/99528800-7db19780-29a7-11eb-9176-a5b781fc5dbf.png)

**Comment by Shelex** [comment]
@talmai-dorel Glad it helped! Basically it just shows the percentage how much of your viewport fits in opened window accordingly to your display resolution. 
In my case with 13.3" laptop and 2560x1600 res I always have 95% for 1000x660 but if I set viewport to 980x630 i will get 100%.

**Comment by talmai-dorel** [comment]
Thanks for the answer @Shelex, so how can you explain that when i am doing cypress open for my project with the same viewport and the same laptop the percentage is 67% 
![image](https://user-images.githubusercontent.com/70937586/99533747-0f70d300-29af-11eb-9b4b-3d936398945c.png)

**Comment by Shelex** [comment]
> Thanks for the answer @Shelex, so how can you explain that when i am doing cypress open for my project with the same viewport and the same laptop the percentage is 67%
> ![image](https://user-images.githubusercontent.com/70937586/99533747-0f70d300-29af-11eb-9b4b-3d936398945c.png)

@talmai-dorel I have no idea. I guess it would be better to clarify that with cypress representatives.

**Comment by talmai-dorel** [comment]
@Shelex tnx
