### ISSUE TITLE
defineSuiteLabels function is not working

### ISSUE THREAD

**Issue by fdiori628** [Shelex/cypress-allure-plugin#154]
**Describe the bug**
I add below script to support/e2e.js, and the suite is still displayed as old one.  Is there any step I missed for this?
Cypress.Allure.reporter
    .getInterface()
    .defineSuiteLabels((titlePath, fileInfo) => {
        return [fileInfo.name, ...titlePath];
    });

**To Reproduce**
1. add script to support/e2e.js
2. run testing
3. check report - suite 

**Expected behavior**
file name should be displayed in the report instead describe of each test

**Environment (please complete the following information):**
- Cypress version:                                10.7
- OS:                                                     Mac
- report version:                                   2.29.0

**Comment by Shelex** [comment]
Hi @fdiori628 
Thank you for reporting an issue.

The issue root cause is that when just 1 level of describe is used there was a check to set 1 `suite` label and early return, thus not applying custom labels from `defineSuiteLabels`.

The fix is published with v2.29.1
