### ISSUE TITLE
Failed test marked as Skipped under specific circumstances

### ISSUE THREAD

**Issue by JessefSpecialisterren** [Shelex/cypress-allure-plugin#158]
**Describe the bug**
When test retries are enabled and a `beforeEach` hook fails once in an early test and `1 + retries` times in a later test, the later test is marked as Skipped and does not include the failure error message:
![image](https://user-images.githubusercontent.com/36038882/189647685-f28b2d2d-70ba-424a-90d6-4eeeaeca4043.png)
We are holding off updating cypress-allure-plugin because of this bug. We have a lot of skipped tests in our suite by default, so this bug would cause us to overlook failed tests.

**To Reproduce**
1. Clone https://github.com/JessefSpecialisterren/cypress-allure-bug-2 and open a terminal in the cloned repo
2. `npm ci`
3. `npx cypress run`
4. `allure serve` (note: allure2 is not included in the repo, so install it manually if it isn't already on your system)
5. Note the status of test D, and click to open it and check for the presence of an error message

**Expected behavior**
In the allure report, test D should be marked as Broken/Defect and include the failure error message.

**Actual behavior**
In the allure report, test D is marked as Skipped and does not include an error message.

**Environment**
- Cypress version:                                10.7.0
- OS:                                                     Windows 10
- cypress-allure-plugin version:           2.31.0
- allure2 version:                                  2.19.0

**Comment by Shelex** [comment]
Thanks for reporting and for a great repo with issue example.
Just took me some time to realize how to properly define which tests should be failed and which skipped judging by failed mocha hook object :)

Fix released in 2.34.0.

**Comment by JessefSpecialisterren** [comment]
@Shelex thanks for the fix! We've been using it for a while now and all seems well 🙂. Thanks again for making and maintaining this plugin!

**Comment by Shelex** [comment]
@JessefSpecialisterren Thanks!
Glad it helped!
