### ISSUE TITLE
after:spec still not working

### ISSUE THREAD

**Issue by AmirAmArA** [Shelex/cypress-allure-plugin#159]
using the allure plugin when trying to use after:spec plugin it wont load with allureWriter(on,config) , even if try to add the allureReuseAfterSpec : true , removing the allureWriter will give access to the after:spec 

1. running cypress with npx cypress run --config-file cypress.config.ts --env allure=true --browser chrome --headless --spec "TEST FILE"
with allureWriter(on,config) 
2. the after:spec won't enter
3. no error appears

it should enter the after:spec as expected while also producing the allure-results

- Cypress version:                               tried with 10.3.0 and 10.7.0
- OS:                                                     mac monterey
- AllurePlugin : tried 2.26.5 / 2.23.0 / 2.31.0 / 2.30.3

**Comment by Shelex** [comment]
Hi @AmirAmArA 
Thank you for opening an issue.
Probably you have cypress v10+ and some other plugins that may utilize that event.
Thus, I would recommend to try `allureReuseAfterSpec: true` env variable configuration.
More details here, second item: https://github.com/Shelex/cypress-allure-plugin#troubleshooting

**Comment by AmirAmArA** [comment]
Hey @Shelex thanks for your response !
this is what i tried but no success, is there a way to see who used the plugin ?

**Comment by Shelex** [comment]
> Hey @Shelex thanks for your response ! this is what i tried but no success, is there a way to see which plugin used the event ?

I am afraid without debugging/checking sources we would not be able to define which dependency registered specific event listener.
Maybe you can provide an example repo where it could be reproduced?

**Comment by AmirAmArA** [comment]
i will try to recreate it with a reproduced issue, 
i was hoping for a guide to try and debug from my end,
or send any kind of logs.

**Comment by AmirAmArA** [comment]
Hey @Shelex this is a bit weird, 

i upgraded to Cypress 10.8 and allure 2.31 and tested it and it is working properly ,
afterwards i downgraded the cypress back to 10.3 and it is still working , 

i also made sure of the arrangement of the env variables and put them before the e2e inside the defineConfig, it's strangely working Now

**Comment by Shelex** [comment]
> lso made sure of the arrangement of the env variables and put them before the e2e inside the defineConfig, it's strangely working Now

Hmm, maybe there is an issue with env vars declared just in `e2e`...
Will re-check it on my side as well.

Anyway, glad it is working fine now :)

**Comment by AmirAmArA** [comment]
thanks for your availability :)
