### ISSUE TITLE
Plugin is using uuid which is not listed in dependencies

### ISSUE THREAD

**Issue by kirill-konshin** [Shelex/cypress-allure-plugin#16]
**Describe the bug**

Plugin is using uuid package https://github.com/Shelex/cypress-allure-plugin/search?q=uuid&unscoped_q=uuid which is not listed in dependencies: 

![image](https://user-images.githubusercontent.com/1530410/87726765-89305000-c774-11ea-9e96-3b7bc8bf040c.png)

```
  Error: @shelex/cypress-allure-plugin tried to access uuid, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
 Required package: uuid (via "uuid")
 Required by: @shelex/cypress-allure-plugin@npm:1.7.3 (via /builds/web-modules/web-modules-core/.yarn/cache/@shelex-cypress-allure-plugin-npm-1.7.3-fce6065109-3f2ae075be.zip/node_modules/@shelex/cypress-allure-plugin/)
 Require stack:
 - /builds/web-modules/web-modules-core/.yarn/cache/@shelex-cypress-allure-plugin-npm-1.7.3-fce6065109-3f2ae075be.zip/node_modules/@shelex/cypress-allure-plugin/writer.js
```

**Comment by Shelex** [comment]
Thank you for opening issue?
Do you experience it while installation process?

**Comment by Shelex** [comment]
@kirill-konshin Another question - is it Yarn 2 with pnp mode?

**Comment by kirill-konshin** [comment]
Error occurs during runtime. And yes, Yarn 2 in PNP mode was used.

**Comment by Shelex** [comment]
@kirill-konshin Added "uuid" dependency version same as used in "allure-js-commons". Issue should be gone.

**Comment by kirill-konshin** [comment]
Thank you!
