### ISSUE TITLE
Environment values not displayed

### ISSUE THREAD

**Issue by mudit94** [Shelex/cypress-allure-plugin#160]
**Is your feature request related to a problem? Please describe.**
Environment section always shows not found

**Describe the solution you'd like**
Environment section should show the OS, and browser details

**Additional context**

**Comment by swatinigam** [comment]
Hi @Shelex I have the same issue that is noted above. We use browserstack to run our cypress-cucumber tests. We run the tests on different OS-browser combinations provided by browserstack. How can we populate the OS and browser in the environment variables widget of allure report?

I'd also like to be able to surface information about the testing environment- like production or qa. Could you suggest how I could go about doing that? Thank you!

**Comment by mmisty** [comment]
@swatinigam 
while it is not supported in this package you can do it by creating file `environment.properties`  in your `allure-results` folder with all env vars you want to include similar to: 
```env
# environment.properties
CYPRESS_VERSION=12.7.0
BROWSER=Chrome
```
You can put `environment.properties` file writing into your plugins: cypress.config.ts -> `setupNodeEvents` function

**Comment by Shelex** [comment]
@swatinigam 
Actually, there is a repo with all examples of this plugin: https://github.com/Shelex/cypress-allure-plugin-example

environment information is here - [cypress/e2e/examples/environment.info.cy.js](https://github.com/Shelex/cypress-allure-plugin-example/blob/master/cypress/e2e/examples/environment.info.cy.js)

and example of the report - https://shelex.github.io/cypress-allure-plugin-example

Or you can do as @mmisty kindly suggested - just write the file on CI during tests start (or end).

This plugin already contains a lot of "bells and whistle" features which are problematic to maintain as they are not used or their usage is questionable, so I would recommend to prepare env variables section on your side to have more control over your report content.
