### ISSUE TITLE
Video and screenshot not attached to Allure report in Cypress 10+

### ISSUE THREAD

**Issue by youvegotnigel** [Shelex/cypress-allure-plugin#161]
**Describe the bug**
Hi!
I'm using allure with cucumber and cypress(10.7). After test execution, I want to generate the allure report and the cucumber.json file and generate a cucumber HTML report.
But seems like even though the allure report is generated, the screenshots and video are not attached to the report if a test has failed.

**To Reproduce**
Clone this repo: https://github.com/youvegotnigel/cypress-cucumber-allure-demo
Execute below commands
`npm run cy:run`
`npm run allure:report`
Open allure report in VS Code live server and check the failed scenario

**Expected behavior**
When test is failed the screenshot and video should be attached to the Allure report.

**Actual behavior**
When the test is failed the screenshot and video are **not** attached to the Allure report.

**Environment (please complete the following information):**
- Cypress version:                                10.7.0
- OS:                                                     Windows

** Developer Tools Console Output **

**Additional context**
I have noticed that when the `cypress.config.js` is written in this order the attachments are working fine but then the I'm not able to generate the cucumber.json file.
```
const { defineConfig } = require("cypress");
const allureWriter = require('@shelex/cypress-allure-plugin/writer');
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const addCucumberPreprocessorPlugin = require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;

module.exports = defineConfig({
  e2e: {
    
    async setupNodeEvents(on, config) {
      const bundler = createBundler({
        plugins: [createEsbuildPlugin(config)],
      });

      on("file:preprocessor", bundler);
      await addCucumberPreprocessorPlugin(on, config);
      allureWriter(on, config);
      return config;
    },
    specPattern: "cypress/e2e/features/*.feature",
    baseUrl: "https://www.saucedemo.com",
    chromeWebSecurity: false,
  },
});
```
I'm hoping for a solution where I can generate both the cucumber and allure reports :)

Can you suggest a workaround where I can generate both the Allure report with screenshots and video attached and the cucumber.json file.?

**Comment by Shelex** [comment]
Hi @AmirAmArA
Thank you for opening an issue.

cypress-allure-plugin uses `after:spec` event to track results and attachments from cypress, which is also used by `cypress-cucumber-preprocessor`.
Thus, I would recommend to try `allureReuseAfterSpec: true` env variable configuration (it applies workaround solution and will listen to nodejs process events directly and intercept the after:spec if it is already registered by some other plugin in Cypress).
More details here, second item: https://github.com/Shelex/cypress-allure-plugin#troubleshooting

**Comment by youvegotnigel** [comment]
Hi @Shelex :) 
Thank you for the quick response.
I updated the cy:run method to `npx cypress run --env allureReuseAfterSpec=true --env allure=true --browser chrome`
But still, I am not able to get the Allure report with the failed screenshot and the video attached :(

**Comment by youvegotnigel** [comment]
Hi @Shelex,
Actually, I updated the cypress.config.js as below add it worked. Thank you for your suggestion.
```
module.exports = defineConfig({
  e2e: {
    
    async setupNodeEvents(on, config) {
      const bundler = createBundler({
        plugins: [createEsbuildPlugin(config)],
      });

      on("file:preprocessor", bundler);
      allureWriter(on, config);
      await addCucumberPreprocessorPlugin(on, config);
      return config;
    },
    env: {
      allure: true,
      allureReuseAfterSpec: true,
      allureResultsPath: 'allure-results',
    },
    specPattern: "cypress/e2e/features/*.feature",
    baseUrl: "https://www.saucedemo.com",
    chromeWebSecurity: false,
  },
```

**Comment by Shelex** [comment]
> 

FYI: env variables should be passed in 1 `--env`argument:
`npx cypress run --env allureReuseAfterSpec=true,allure=true --browser chrome`

**Comment by Shelex** [comment]
> Hi @Shelex :) Thank you for the quick response. I updated the cy:run script to `npx cypress run --env allureReuseAfterSpec=true --env allure=true --browser chrome` in the package.json file. But still, I am not able to get the Allure report with the failed screenshot and the video attached :(

FYI: env variables should be passed in 1 `--env`argument:
`npx cypress run --env allureReuseAfterSpec=true,allure=true --browser chrome`
