### ISSUE TITLE
Cypress screenshots not successfully generated

### ISSUE THREAD

**Issue by sjyzheng** [Shelex/cypress-allure-plugin#171]
We have an issue displaying the screenshots in the Allure report. This is a GitLab CI integration. The allure-results folder has the screenshots, and the result.json file has the images' information in it.

![Screen Shot 2022-10-27 at 09 40 58](https://user-images.githubusercontent.com/59863441/198349586-ce0f69d6-4649-4d7c-883f-a436db488d8b.png)

![Screen Shot 2022-10-27 at 09 41 38](https://user-images.githubusercontent.com/59863441/198349643-eecc3f87-660e-470b-a538-8321e79d93fe.png)

Allure is not able to create the data/attachments folder and load the screenshots to it.

![Screen Shot 2022-10-27 at 09 46 53](https://user-images.githubusercontent.com/59863441/198350569-c21fee57-0fd6-4fe9-be2b-dea03b66da74.png)

In the Allure report, the screenshots are listed with 0 B file size, they are not clickable, and cannot be opened:

![Screen Shot 2022-10-27 at 09 48 05](https://user-images.githubusercontent.com/59863441/198350957-7339a46a-a3e8-482e-84e6-34834acca0cf.png)

We are using cypress-allure-plugin v2.26.5. 

This issue may be related to the previously reported bug - [Issue-12](https://github.com/Shelex/cypress-allure-plugin/issues/12)

**Comment by sjyzheng** [comment]
Hi @Shelex,

Thank you so much for your response. We have upgraded both the allure and cypress-allure-plugin to the latest version, but the issue persists. 

I am wondering if it could be because the attachment name in the allure result json file has invalid characters - "tests/UI/OCAMP/e2e/campaign_duplication.spec.js:2022-10-25T16:35:26.516Z"

![198349586-ce0f69d6-4649-4d7c-883f-a436db488d8b](https://user-images.githubusercontent.com/59863441/212361544-8e7c9d88-5011-4d96-8478-34689bbe2347.png)

Please advice.

Thanks!

**Comment by sjyzheng** [comment]
And the issue is similar to the previously reported bug - [See issue 12](https://github.com/Shelex/cypress-allure-plugin/issues/12)

**Comment by Shelex** [comment]
Hi @sjyzheng 

Some example repo where issue could be reproduced would be the best help for figuring out what may go wrong.

You can try https://github.com/Shelex/cypress-allure-plugin-example and play with it.

I think there may be some code issues or configuration, for example if you don't have plugins (like cucumber) that utilize `after:spec` cypress event, `allureReuseAfterSpec` should not be used or be set to `false`, or there may be something else...

**Comment by Shelex** [comment]
Please reopen if it still occurs or you have some example where it could be reproduced, closing for now as issue is inactive.
