### ISSUE TITLE
allureClearSkippedTests doest not work correctly

### ISSUE THREAD

**Issue by JohnnyChiang** [Shelex/cypress-allure-plugin#173]
**Describe the bug**
When running Cypress with `allureClearSkippedTests` option. Skipped tests become `pending` status

**To Reproduce**
1. Run the following test with
`$(npm bin)/cypress run --env allure=true,allureClearSkippedTests=true --spec="cypress/integration/test.js"`
``` javascript
describe('suite 1', function () {
    beforeEach(function () {
        cy.visit('notExistingUrl')
    })

    it('t1', function () {
        cy.log('t1')
    })

    it('t2', () => {
        cy.log('t2')
    })
})

describe('suite2', function () {
    it.skip('t3', function () {
        cy.log('t3')
    })
})
```
2. `allure serve`
The skipped test leaves `pending` status in `allure-results` folder and becomes unknown status in the report
![螢幕快照 2022-11-15 上午7 43 51](https://user-images.githubusercontent.com/2437629/201793969-9cb082c0-24a6-455c-a833-6d4e80d39c09.png)

**Expected behavior**

**Environment (please complete the following information):**
- Cypress version:                                8.5.0
- OS:                                                      Mac(Mojave 10.14.6)
- cypress-allure-plugin version:         2.27.1

**Developer Tools Console Output**
```
  allure-plugin:writer starting writing allure results to "allure-results" +5s
  allure-plugin:writer clearing skipped tests enabled, removing tests from suite suite 1 +0ms
  allure-plugin:writer write suite "suite 1" to file "bd438064-8e72-4956-a973-7896c4fab2a2-container.json" +1ms
  allure-plugin:writer clearing skipped tests enabled, removing tests from suite suite2 +0ms
  allure-plugin:writer skip suite as it has no tests remained +0ms
  allure-plugin:writer write test "t1" to file "18ce4d16-c068-4a21-9e8e-ea43e4bae2ff-result.json" +0ms
  allure-plugin:writer write test "t2" to file "ae43428c-b445-46f3-97ba-ec48153182e2-result.json" +1ms
  allure-plugin:writer skipping test "t3" +0ms
  allure-plugin:writer finished writing allure results +0ms
  allure-plugin:writer inside "after:spec" event +1s
  allure-plugin:writer processing "after:spec" results +0ms
  allure-plugin:writer going to check attachments for "18ce4d16-c068-4a21-9e8e-ea43e4bae2ff" +1ms
  allure-plugin:writer going to attach screenshot to "18ce4d16-c068-4a21-9e8e-ea43e4bae2ff" +1ms
  allure-plugin:writer copying screenshot from "xxx/test_allure/cypress/screenshots/test.js/suite 1 -- t1 -- before each hook (failed).png" to "allure-results/0c80346a-1779-4106-8ab1-2331b66b6de0-attachment.png" +0ms
  allure-plugin:writer going to attach video for "18ce4d16-c068-4a21-9e8e-ea43e4bae2ff" +1ms
  allure-plugin:writer going to check attachments for "ae43428c-b445-46f3-97ba-ec48153182e2" +0ms
  allure-plugin:writer going to attach video for "ae43428c-b445-46f3-97ba-ec48153182e2" +1ms
  allure-plugin:writer going to check attachments for "64ba642e-0b23-4c84-a6f9-b8eaf95117bb" +0ms
  allure-plugin:writer going to attach video for "64ba642e-0b23-4c84-a6f9-b8eaf95117bb" +1ms
  allure-plugin:writer found 3 tests that require video +0ms
  allure-plugin:writer copying video from "xxx/Desktop/test_allure/cypress/videos/test.js.mp4" to "allure-results/c1857a66-9134-4e89-9db8-fd5a9ac52166-attachment.mp4" +0ms
```

**Additional context**
Everything works fine in Cypress version 6.6.0.

**Comment by AKlavins** [comment]
Hello! I'm also having the same issue

**Comment by Shelex** [comment]
Released in v2.34.1

The reason is that skipped tests were actually removed, but then in `after:spec` event there is additional check of tests which require attachments and if there was no test - it is created, because it may be due to crash or any other reason. So I have just removed id's of skipped tests from that attachments check and it should work fine.

**Comment by marcrecor** [comment]
@Shelex 
This bug is happening again.
    "@badeball/cypress-cucumber-preprocessor": "~17.2.0",
    "@shelex/cypress-allure-plugin": "^2.40.0",
    "cypress": "~12.14.0",

**Comment by kandji-joel** [comment]
@Shelex can we re-open this or do we need a new ticket. Looks like this regressed shortly after the fix
