### ISSUE TITLE
Uncaught TypeError: path.parse is not a function  

### ISSUE THREAD

**Issue by MaksimYaginov** [Shelex/cypress-allure-plugin#178]
Hi! I had a problem after switching from version 2.29.0 to version 2.29.1. Cypress version 11.2.0

defineSuites.js:7 Uncaught TypeError: path.parse is not a function
    at parseAbsolutePath (defineSuites.js:7:1)
    at defineSuites (defineSuites.js:24:1)
    at AllureReporter.startCase (AllureReporter.js:215:1)
    at Runner.eval (index.js:120:1)

Please help solve the problem)

**Comment by MaksimYaginov** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/31980692/209842822-e7706bd0-0caa-401e-9f2e-7a6ae690ab81.png">

**Comment by MaksimYaginov** [comment]
i added path-browserify to package.jsion - it solved the problem

**Comment by Shelex** [comment]
Just upgrade to latest version, I remember such issue was fixed previously.
