### ISSUE TITLE
Tests within the same script are marked as skipped after a domain change

### ISSUE THREAD

**Issue by nlclarke** [Shelex/cypress-allure-plugin#179]
**Describe the bug**
Tests within the same script are marked as skipped after a domain change.

If cy.visit() is executed on multiple "new" domain within the same test script, the Cypress Runner is refreshed/cleared. 

All test cases that were executed before each restart are marked skipped in the generated json files and report. 

Test Code to Reproduce:
https://github.com/nlclarke/cypress-allure-plugin-issue-1
(Steps to run included in readme)

In this example, all but the last test case are marked as skipped despite being run successfully.

**To Reproduce**
1. Create a cypress script with 2 or more test case where you visit a different domain for each test 
2. Observe the generated allure test results to see that tests prior to last domain change are marked as skipped

**Expected behavior**
All test cases should have the correct result status

**Environment (please complete the following information):**
- Cypress version:                                12.2.0
- OS:                                                     Windows
- cypress-allure-plugin version:           2.34.0

**Comment by Shelex** [comment]
Hi @nlclarke 
Issue is resolved in v2.38.3

[Example report](https://shelex.github.io/cypress-allure-plugin-example/57/#suites/c67787c46d2c74fa6f67f219a5af6035/53b83a481d35ccbc/)

**Comment by nlclarke** [comment]
Great everything looks to be working on my end. Thank you!
