### ISSUE TITLE
Unable to generate allure-results folder after test execution is complete!!

### ISSUE THREAD

**Issue by pvishnu991** [Shelex/cypress-allure-plugin#18]
I have configured the Cypress-allure-plugin within the package.json as suggested in the description and copied over the codes to plugin/index.js and support/index.js, also set an environment variable to customize the path for the allure-results. 
Upon running the tests the allure-results folder is not generated automatically.

1. Installing cypress allure plugin
2. Configuration  as suggested in the below link
https://github.com/Shelex/cypress-allure-plugin
3. Set the env variable to customize the path for reports
3. Run the test :  npx cypress-tags run -e TAGS='@tags' --env allure=true allureResultsPath=cypress/results --browser chrome

**Expected behavior**
The allure-results folder should get displayed.

Failure Message:

The task '**writeAllureResults**' was not handled in the plugins file. The following tasks are registered: hasSavedRecord, connectDataBase, updateDataBase, getMerchantIDfromDataBase, fetchMultiVariableDataBase, fetchVariableDataBase, connectAsync, testStart, clearPreviousAttemptScreenshots

**Environment (please complete the following information):**
- Cypress version:                                4.3
- OS:                                                     Windows

**Comment by Shelex** [comment]
Hello @pvishnu991! Thank you for posting an issue.

I have not managed to catch such error, so could you please provide repo with reproducible example of your setup?
Issue `The task 'writeAllureResults' was not handled` means that task was not registered, so I guess it is because of some peculiarities of your `cypress/plugins/index.js` file. 
Please ensure that writer.js module is required in your plugins file and patched the config:
```
allureWriter(on, config);
return config;
```

**Comment by pvishnu991** [comment]
Hi @Shelex ,

Thanks for that response.
Since i do have a limitation in publishing the entire code pack which we are working on , i am sharing the screenshots where in i have added the configurations as suggested for the plugin.

I have the below configurations under plugins/index.js
![image](https://user-images.githubusercontent.com/47185544/90769275-e07f8e00-e2e7-11ea-8f09-950f65564337.png)

support/index.js
![image](https://user-images.githubusercontent.com/47185544/90769367-06a52e00-e2e8-11ea-9b45-5c7046b245a3.png)

cypress.json

![image](https://user-images.githubusercontent.com/47185544/90769393-16247700-e2e8-11ea-8c05-989698f9f40e.png)

jsconfig.json

![image](https://user-images.githubusercontent.com/47185544/90769582-64397a80-e2e8-11ea-8c09-7b7bd92d0230.png)

Also i am using version 4.3 for cypress. Would that possible cause any issue for this plugin to work with. 
It would be really great if i could get a work around for this as we are kind of blocked in generation of reports for our tests in allure.

Much Thanks
Vishnu

**Comment by Shelex** [comment]
@pvishnu991 webpack is used for typescript support?

**Comment by pvishnu991** [comment]
hi ,

i just introduced it cause we already have it under package.json. I even tried within this and still it doesnt give any allure-results folder!!

Thanks

**Comment by Shelex** [comment]
@pvishnu991 
In case you are not using webpack, in plugins/index.js:
```
const allureWriter = require('@shelex/cypress-allure-plugin/writer');

module.exports = (on, config) => {
    allureWriter(on, config);
    return config;
};
```
In support/index.js you don't need to importthis plugin twice, just leave line with require:
`require('@shelex/cypress-allure-plugin');`

**Comment by pvishnu991** [comment]
Thats perfect!!
I guess it was an issue with placing the allurewriter module. We have loads of tasks within the module exports under plugins/index.js .
It is working perfectly now. 
Thanks a million for that @Shelex
