### ISSUE TITLE
Cucumber: The allure report logs the steps in inverse order

### ISSUE THREAD

**Issue by thienthu1410** [Shelex/cypress-allure-plugin#181]
**Describe the bug**
Cucumber: The allure report logs the steps in inverse order

**To Reproduce**
1. Get the example from https://github.com/Shelex/cypress-allure-plugin-example
2. Run npm install
3. Run the test
4. Run the command to generate the allure report
5. Run the command allure report to open the report
6. Viewing the report, I see that the sub-steps inside the gherkin steps are logged in the inverse order

The steps definition:
![image](https://user-images.githubusercontent.com/15967414/213393040-2e96c248-08ef-4b14-8cea-901856f6b079.png)

The allure report:
![image](https://user-images.githubusercontent.com/15967414/213393162-c24115f4-983c-4fad-9252-2fe7175b87cc.png)

**Expected behavior**
The order is logged in the proper order

**Environment (please complete the following information):**
- Cypress version:                                12.3.0
- OS:                                                     Windows
** Developer Tools Console Output **

**Additional context**

**Comment by Shelex** [comment]
Released in v2.34.1
