### ISSUE TITLE
How to view test history when running Cypress tests locally

### ISSUE THREAD

**Issue by jprealini** [Shelex/cypress-allure-plugin#185]
I know Allure reporter let's us save the execution history and see it in the report.. I have tried to setup something based on examples I saw published here and there, but all I could achieve was to see last two executions.... not sure what I am doing wrong. I am running Cypress 10.3

Anyone could provide a link to documentation regarding how to setup, run and save test history in Cypress with Allure? 

Thanks

**Comment by Shelex** [comment]
Hi.
Basically, Cypress has nothing to do with allure or allure history, tests are finished, runner is done, that is it.

In few words, "history" means that we have access to some previous data. In Allure it is achieved by generating folder `allure-report/history` with metadata about current execution.
To pass it to the next execution, you should take this `allure-report/history` folder and copy into `allure-results/history` folder and generate new report. The same step is repeated for each new report you generate - just grab the `history` from existing one.

- I have example of implementing it with github actions where all this "magic" encapsulated in 3rd party actions: [cypress-allure-plugin-example](https://github.com/Shelex/cypress-allure-plugin-example)
- I have found just tiny mention of this in their docs - [History files](https://docs.qameta.io/allure/#_history_files)

Hope this helps.

**Comment by jprealini** [comment]
@Shelex it sure did! Thanks... I was having two main issues:
1. Not sure how that flow should go
2. In order to see this working I am running Cypress locally on windows, so the allure:history script was failing (due to mv and rm not working properly in my OS...) I managed to solve that by doing this
```
"allure:history": "rm -r allure-results/history && mv -f allure-report/history allure-results && rm -r allure-report || true",
```
I have now a particular question about "broken tests" in report, but that's something for another thread 😄 

Thanks again!
