### ISSUE TITLE
API request still doesn't attach results to the report.

### ISSUE THREAD

**Issue by kunalashar25** [Shelex/cypress-allure-plugin#189]
@Shelex Can you please cross-check once, it still doesn't attach results to the report. 
Checking with `v2.35.0`

_Originally posted by @kunalashar25 in https://github.com/Shelex/cypress-allure-plugin/issues/174#issuecomment-1413295931_

**Comment by Shelex** [comment]
@kunalashar25 indeed, support of logging requests from `cy.api` plugin required additional implementation.
Released in v2.37.0.

**Comment by Shelex** [comment]
Verified in `cypress-allure-plugin-example` repo [test](https://github.com/Shelex/cypress-allure-plugin-example/blob/master/cypress/e2e/examples/cypress.log.cy.js#L41)
Report [example](https://shelex.github.io/cypress-allure-plugin-example/53/#suites/49c6182d51734400515617e246552c75/6d2b242e344562a9/)
