### ISSUE TITLE
There are no any attachments in report

### ISSUE THREAD

**Issue by ssgorbunkov67** [Shelex/cypress-allure-plugin#190]
cypress.config.ts

const { defineConfig } = require("cypress");
const cucumber = require('cypress-cucumber-preprocessor').default;
const allureWriter = require("@shelex/cypress-allure-plugin/writer");
const browserify = require('@cypress/browserify-preprocessor');

module.exports = defineConfig({
    e2e: {
        async setupNodeEvents(on, config) {
           const options = {
        ...browserify.defaultOptions,
        typescript: require.resolve("typescript"),  
    }
            on('file:preprocessor', cucumber(options));
            allureWriter(on, config);
            return config

        },
        env: {
            allure: true,
            allureReuseAfterSpec: true,
            allureResultsPath: 'results/allure',
        },
        specPattern:"cypress/integration/**/*.feature",
        baseUrl: 'http://localhost:8080',
    },
});

Directory 'results/allure' always created but there are only json files their. There are no any *.png, *.mp4 files there.
In directory screenshots in project the images are being created successfully!

Do you have any ideas?

**Comment by ssgorbunkov67** [comment]
Solving the problem for my case!
Perhaps it will be useful to someone. There are no attachments on the last version.(2.35.2) and all versions older(2.21....) Everything is ok with "@shelex/cypress-allure-plugin": "2.20.0"

**Comment by Shelex** [comment]
Closing this as there were fixes in terms of 2.36.0 which may have caused missing screenshots.
Please try latest version, if issue still reproduces prepare an example repo were it could be checked with your specific case.
