### ISSUE TITLE
Pictures are not clickable in report html

### ISSUE THREAD

**Issue by Karnikel** [Shelex/cypress-allure-plugin#20]
**Describe the bug**
If a screenshot or a diff-screenshot was taken during test run...it is listed at each test result in report as filename, but it isn't clickable

**To Reproduce**
1. Execute a test where a screenshot is taken
2. Generate a report
3. Open this report and try to click on the line of the testexecution log where the screenshot is mentioned

**Expected behavior**
If I click on the screenshot name in the log of the test report, I see it on the page as image, as in previous versions of Cypress-allure-plugin
Retestet with Cypress-Verion 5.0.0 and Cypress-allure-plugin version 1.7.1 --> It works

**Environment (please complete the following information):**
- Cypress version:                                5.00
- Cypress-allure-plugin version:           1.8.2
- OS:                                                    Windows

**Comment by Shelex** [comment]
Hello @Karnikel
Thank you for opening an issue.

Could you please clarify - these are screenshots taken with `cy.screenshot()` or some other plugin?

**Comment by Karnikel** [comment]
Hi @Shelex 
the example would be very simple:
```
describe('test suite', () => {
  it('test case', () => {
    cy.visit(www.google.de);
    cy.screenshot('Testscreenshot made with cy.screenshot()');
    cy.matchImageSnapshot('Testscreenshot made with cypress-image-snapshot');
  });
});
```
After the testrun with `cypress run` the testresults resides (at my framework) in
- `./testresults/report/diffPics/<TestSpec>/<testFileName>/<Image.png>`   Files which are created by cypress-image-snapshot
- `./testresults/report/rawResults/<hash-result.json>`   Files which are created by your plugin

After that I create a html page with the package `allure-commandline` which creates the html report with 3 image references next to the test execution steps.
- One screenshot made by the command cy.screenshot()
- One screenshot made by the command cy.matchImageSnapshot()
- One screenshot made by Cypress by default at the and of each test

But these images are not clickable and the size is also shown with 0B.

**Finaly, the root cause would be, that the directory of the html report `./data/attachments` is empty, if I use Cypress-allure-plugin version 1.8.2**. if i use an older version, the dir containing all images which are referenced in report.
Hope that helps...

**Comment by Shelex** [comment]
@Karnikel Should have been fixed in v1.10.1, could you please check it on your side?

**Comment by Karnikel** [comment]
@Shelex: Sorry for the delay...Your fix works grat. Thanks for solving this.
Hint: I tested it with v1.10.1...Version 2.0.0 creates a report html with no test report data (NaN).
-> This BUG is solved. Ticket can be closed.

**Comment by Shelex** [comment]
@Karnikel Thank you for verification! Quite strange to see issues with v2 as only difference with 1.10.1 is renamed command for attaching files 🤔
