### ISSUE TITLE
Only single failed screenshot is attached to the report

### ISSUE THREAD

**Issue by kasun-alwis** [Shelex/cypress-allure-plugin#203]
**Describe the bug**
When a test fails there will be multiple screenshots available depending on the retry count. But we only see a single screenshot is attached to the report.

**To Reproduce**
1. Set cypress retry count to 2
2. Run a test and make it fail
3. Open the report

**Expected behavior**
All the screenshots should be attached to the report

**Environment (please complete the following information):**
- Cypress version: 12.9.0
- OS: Mac
- cypress-allure-plugin : 2.38.3

** Developer Tools Console Output **
No error logs available in the console

**Additional context**
![Screenshot 2023-04-17 at 17 31 21](https://user-images.githubusercontent.com/121799299/232538701-31ca5f7a-51f6-4343-9243-758d3c2d6ca7.png)
![Screenshot 2023-04-17 at 17 31 44](https://user-images.githubusercontent.com/121799299/232538708-bdb05236-16ac-42e6-9714-c8b0b63c1a27.png)
![Screenshot 2023-04-17 at 17 32 07](https://user-images.githubusercontent.com/121799299/232538711-fc2c89a7-243e-4d0b-ba41-48ec6a585039.png)

**Comment by samixchoumi** [comment]
We have exactly the same problem. A bit annoying when we need the first failed screenshot instead of the last one.
We have set : `allureOmitPreviousAttemptScreenshots: false` and it's the same.

**Comment by Shelex** [comment]
@kasun-alwis @samixchoumi that may be the change introduced with the feature to persist retried tests, so now attachment should go into retries tab to corresponding test, like in example repo: https://shelex.github.io/cypress-allure-plugin-example/57/#suites/dcd889af27d9a4e43f8b4218e0ff8165/2bec9746035f55f7/retries

Could you please check if retries tab is available with test data and attachments?

**Comment by kasun-alwis** [comment]
@Shelex Even though I set the retry count to `2`, I only see one retry attached to the report.

<img width="801" alt="Screenshot 2023-04-21 at 09 44 05" src="https://user-images.githubusercontent.com/121799299/233730116-8c64b261-f30c-4538-bc5c-2ecb0ae69104.png">


Below are my configurations
package.json : 
`  "devDependencies": {
    "@shelex/cypress-allure-plugin": "^2.38.3",
    "cypress": "^12.10.0",
    "typescript": "^4.9.4"
  },`

cypress.config.ts
`  env: {
    allure: true,
    allureResultsPath: 'allure-results',
    allureLogCypress: true,
    allureReuseAfterSpec: true,
  },
  e2e: {
    setupNodeEvents(on, config) {
      allureWriter(on, config);`

**Comment by Shelex** [comment]
> 

For me it seems like expected outcome - 2 attempts, the latest one is available in report, if you need previous - just check retries tab, which in case of 2 attempts will have another 1 left.

**Comment by kasun-alwis** [comment]
Closing the ticket since we can see the failed results on the retries tab

<img width="509" alt="Screenshot 2023-07-18 at 09 52 36" src="https://github.com/Shelex/cypress-allure-plugin/assets/121799299/578b549f-2006-4f1c-900f-77c9de7a7e63">
