### ISSUE TITLE
Test cases with same name across multiple specs get recognized as one

### ISSUE THREAD

**Issue by ktxxt** [Shelex/cypress-allure-plugin#209]
**Describe the bug**
I have 2 spec files:
 - a.cy.ts
 - b.cy.ts

Both spec files have the following code

```js
it('Create model', () => {
  // some code
})
```

In the report they are recognized as one(overwritten as it seems).

**Expected behavior**
They should be recognized as different tests if they're in separate spec files.

**Environment (please complete the following information):**
- Cypress version:                                12.12.0
- OS:                                                     Linux (Ubuntu):
- cypress-allure-plugin                          2.39.1

**Comment by ktxxt** [comment]
Is there any workaround where I can get the expected behavior?

**Comment by ParTee71** [comment]
+1

**Comment by begli80** [comment]
I have the same issue , if different spec files  contain the same test case description, gets recognized as one

**Comment by Shelex** [comment]
Indeed, that is the behavior of allure reporter.

https://github.com/allure-framework/allure2/issues/1196
https://github.com/allure-framework/allure2/issues/1058

> Is there any workaround where I can get the expected behavior?

In v2.40.0 have added a way to specify what will be used to calculate historyId for Allure to separate tests by their file path, or browser, or anything else you would like.

docs - https://github.com/Shelex/cypress-allure-plugin#test-name-duplicates

example - https://shelex.github.io/cypress-allure-plugin-example/59/#suites/f06e574df226f26e791c6a61c44ed2d8/c5b8ba3c7e61f9d8/

**Comment by ktxxt** [comment]
Thanks a lot!

**Comment by ParTee71** [comment]
Thanks! :)
