### ISSUE TITLE
How to customize logo, title and sections in the report?

### ISSUE THREAD

**Issue by mromero14** [Shelex/cypress-allure-plugin#219]
I work with cypress (12) integrated with allure. I need to change the logo, the  title and hide a tab. Please could you comment if we have this option?

**Comment by mromero14** [comment]
@Shelex could you help me with this configuration?

**Comment by Shelex** [comment]
@mromero14 I have no other information other than https://stackoverflow.com/questions/48709263/how-to-customize-allure-report-title-and-logo
