### ISSUE TITLE
Screenshots not getting attached?

### ISSUE THREAD

**Issue by bahunov** [Shelex/cypress-allure-plugin#22]
**Describe the bug**
Screenshots not getting attached on latest version, data/attachments folder is empty although a screenshot is created..

Empty attachments from report
![image](https://user-images.githubusercontent.com/22296212/93750599-c7cb0680-fc0c-11ea-9c90-ad63434de025.png)

Screenshots in cypress
![image](https://user-images.githubusercontent.com/22296212/93750752-0bbe0b80-fc0d-11ea-8957-56bdf84e2fb6.png)

Empty attachments folder:
![image](https://user-images.githubusercontent.com/22296212/93750769-12e51980-fc0d-11ea-8dfd-4d21d5f9484e.png)

**Expected behavior**

**Environment (please complete the following information):**
- Cypress version:                                5.1.0
- OS:                                                      Mac
- allure-report                                      1.8.2

** Developer Tools Console Output **

**Additional context**

**Comment by bahunov** [comment]
I can see the attached video being correctly referenced: in the json:
"type":"video/mp4",
"source":"**../cypress/videos**/smoke.spec.js.mp4"

As for the screenshot/png the source is incorrect:
"name":"smoke.spec.js:2020-09-21T12:15:48.434Z",
"type":"image/png",
"source":"test smoke -- should give warning (failed).png"}

The source should be:
../cypress/screenshots/smoke.spec.js/test smoke -- should give warning (failed).png

**Comment by bahunov** [comment]
Problem solved! I had mixed up my plugin index.js.. Allure should be last if you have multiple plugins I believe:

```
module.exports = (on, config) => {
 
  require('cypress-image-snapshot/plugin').addMatchImageSnapshotPlugin(on, config)
  AllureWriter(on, config);
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  return config
}
```

**Comment by Shelex** [comment]
@bahunov thank you for opening issue and I am glad that you have resolved your case. Will check how multiple plugins operating within cypress, especially `cypress-image-snapshot` and allure, as that behaviour is not obvious for now.
