### ISSUE TITLE
Custom Video Path

### ISSUE THREAD

**Issue by kpittman-securus** [Shelex/cypress-allure-plugin#23]
In the docs it says to open an issue if you are using a custom path for videos. 

https://github.com/Shelex/cypress-allure-plugin#screenshots-and-videos
> [...] for now default videos path is used: cypress/videos. Please open a feature request in case you are using custom folder paths.

I have inherited a project where there is a lot of existing stuff built around using the folder `output`... like `output/reports`, `output/video`, `output/screenshots`, etc.

It appears that the screenshots work fine from within this folder.

In Allure, the video attachments are displayed alongside failed tests, but they are 0 bytes and do not work.

It would be nice if there were some way I could have them linked correctly!

Please let me know if there's anything I could do to help.

**Comment by Shelex** [comment]
@kpittman-securus Hey! Thank you for opening an issue.
Support for custom video path should be available in v1.8.3

**Comment by kpittman-securus** [comment]
Tested and works perfectly! Thanks @Shelex!
