### ISSUE TITLE
TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by Neethas16** [Shelex/cypress-allure-plugin#25]
I am getting below Error for my package while loading the page.

TypeError: Cannot read property 'config' of undefined
    at eval (webpack-internal:///./src/pages/Dynamo.tsx:5:5)
    at Object../src/pages/Dynamo.tsx (/workplace/neethas/ART_web_Testing/src/ARTWeb_testing/.next/server/pages/Dynamo.js:103:1)
    at __webpack_require__ (/workplace/neethas/ART_web_Testing/src/ARTWeb_testing/.next/server/pages/Dynamo.js:23:31)
    at /workplace/neethas/ART_web_Testing/src/ARTWeb_testing/.next/server/pages/Dynamo.js:91:18
    at Object.<anonymous> (/workplace/neethas/ART_web_Testing/src/ARTWeb_testing/.next/server/pages/Dynamo.js:92:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/workplace/neethas/ART_web_Testing/src/ARTWeb_testing/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .js] (/workplace/neethas/ART_web_Testing/src/ARTWeb_testing/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)

My Index.config.js file
// eslint-disable-next-line @typescript-eslint/no-var-requires
const artConfig = require("@amzn/art-next-configuration");

const stage = (process.env.STAGE || "local").toLowerCase();
const isRDE = process.env.IS_RDE;

function getAssetPrefix(stage) {
  return stage === "local" || isRDE === "true"
    ? ""
    : // TODO: add your CloudFront URL here
      "https://<distribution>.cloudfront.net/assets";
}

module.exports = artConfig({
  distDir: ".next",
  assetPrefix: getAssetPrefix(stage),
});

module.exports = {
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: 'empty'
      }
    }

    return config
  }
}

my index,js file

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var os_1 = require("os");
var path_1 = require("path");
var fs_1 = require("fs");
exports.ENV_CREDENTIALS_PATH = 'AWS_SHARED_CREDENTIALS_FILE';
exports.ENV_CONFIG_PATH = 'AWS_CONFIG_FILE';
var swallowError = function () { return ({}); };
function loadSharedConfigFiles(init) {
    if (init === void 0) { init = {}; }
    var _a = init.filepath, filepath = _a === void 0 ? process.env[exports.ENV_CREDENTIALS_PATH]
        || path_1.join(getHomeDir(), '.aws', 'credentials') : _a, _b = init.configFilepath, configFilepath = _b === void 0 ? process.env[exports.ENV_CONFIG_PATH]
        || path_1.join(getHomeDir(), '.aws', 'config') : _b;
    return Promise.all([
        slurpFile(configFilepath)
            .then(parseIni)
            .then(normalizeConfigFile)
            .catch(swallowError),
        slurpFile(filepath)
            .then(parseIni)
            .catch(swallowError),
    ]).then(function (parsedFiles) {
        var configFile = parsedFiles[0], credentialsFile = parsedFiles[1];
        return {
            configFile: configFile,
            credentialsFile: credentialsFile,
        };
    });
}
exports.loadSharedConfigFiles = loadSharedConfigFiles;
var profileKeyRegex = /^profile\s(["'])?([^\1]+)\1$/;
function normalizeConfigFile(data) {
    var map = {};
    for (var _i = 0, _a = Object.keys(data); _i < _a.length; _i++) {
        var key = _a[_i];
        var matches = void 0;
        if (key === 'default') {
            map.default = data.default;
        }
        else if (matches = profileKeyRegex.exec(key)) {
            var _1 = matches[0], _2 = matches[1], normalizedKey = matches[2];
            if (normalizedKey) {
                map[normalizedKey] = data[key];
            }
        }
    }
    return map;
}
function parseIni(iniData) {
    var map = {};
    var currentSection;
    for (var _i = 0, _a = iniData.split(/\r?\n/); _i < _a.length; _i++) {
        var line = _a[_i];
        line = line.split(/(^|\s)[;#]/)[0]; // remove comments
        var section = line.match(/^\s*\[([^\[\]]+)]\s*$/);
        if (section) {
            currentSection = section[1];
        }
        else if (currentSection) {
            var item = line.match(/^\s*(.+?)\s*=\s*(.+?)\s*$/);
            if (item) {
                map[currentSection] = map[currentSection] || {};
                map[currentSection][item[1]] = item[2];
            }
        }
    }
    return map;
}
function slurpFile(path) {
    return new Promise(function (resolve, reject) {
        fs_1.readFile(path, 'utf8', function (err, data) {
            if (err) {
                reject(err);
            }
            else {
                resolve(data);
            }
        });
    });
}
function getHomeDir() {
    var _a = process.env, HOME = _a.HOME, USERPROFILE = _a.USERPROFILE, HOMEPATH = _a.HOMEPATH, _b = _a.HOMEDRIVE, HOMEDRIVE = _b === void 0 ? "C:" + path_1.sep : _b;
    if (HOME)
        return HOME;
    if (USERPROFILE)
        return USERPROFILE;
    if (HOMEPATH)
        return "" + HOMEDRIVE + HOMEPATH;
    return os_1.homedir();
}
//# sourceMappingURL=index.js.map

**To Reproduce**
1. Do this
2. Then do that
3. See error

**Expected behavior**

**Environment (please complete the following information):**
- Cypress version:                                #.##
- OS:                                                     Windows | Mac | Linux (distro):

** Developer Tools Console Output **

**Additional context**

**Comment by Shelex** [comment]
Hi @Neethas16 
Thank you for opening issue.

Is this error caused by allure-plugin? In case it is - could you please prepare repository and share a link, so I could reproduce such issue, as with information provided it is not clear at all what is happening.

**Comment by Shelex** [comment]
I guess it may be caused by [mistype in docs](https://github.com/Shelex/cypress-allure-plugin/pull/33/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R49) for ts example where no `config` property was passed in plugins file. 
In case issue still reproduces - please reopen the ticket.
