### ISSUE TITLE
afterEach is not defined if cypress-allure-plugin is added as a report

### ISSUE THREAD

**Issue by archital** [Shelex/cypress-allure-plugin#3]
Could you please help to clarify what I did wrong?
If there is no "reporter" section in my cypress.json file than after run:
`npx cypress run --config video=false --env allure=true --browser chrome` my generated allure report is empty. 

I've tried to paste 

 `  "reporter": "@shelex/cypress-allure-plugin",
   "reporterOptions": {
     "targetDir": "allure"
   },`
  but this time I have got an error:

> `>npx cypress run --config video=false --env allure=true --browser chrome
> 
> Could not load reporter by name: @shelex/cypress-allure-plugin
> 
> We searched for the reporter in these paths:
> 
> - C:\Users\apopi\Perforce\apopichenko\WUG\MAIN\WhatsUp-UI\Web\NMWorkspace\@shelex\cypress-allure-plugin
> - C:\Users\apopi\Perforce\apopichenko\WUG\MAIN\WhatsUp-UI\Web\NMWorkspace\node_modules\@shelex\cypress-allure-plugin
> 
> The error we received was:
> 
> ReferenceError: afterEach is not defined
>     at Object.<anonymous> (C:\Users\apopi\Perforce\apopichenko\WUG\MAIN\WhatsUp-UI\Web\NMWorkspace\node_modules\@shelex\cypress-allure-plugin\reporter\afterHook.js:4:1)
>     at Module._compile (internal/modules/cjs/loader.js:880:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
>     at Module.load (internal/modules/cjs/loader.js:735:32)
>     at Module._load (internal/modules/cjs/loader.js:648:12)
>     at Module._load (electron/js2c/asar.js:717:26)
>     at Function.Module._load (electron/js2c/asar.js:717:26)
>     at Module.require (internal/modules/cjs/loader.js:775:19)
>     at require (internal/modules/cjs/helpers.js:68:18)
>     at Object.<anonymous> (C:\Users\apopi\Perforce\apopichenko\WUG\MAIN\WhatsUp-UI\Web\NMWorkspace\node_modules\@shelex\cypress-allure-plugin\reporter\index.js:1:1)
>     at Module._compile (internal/modules/cjs/loader.js:880:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
>     at Module.load (internal/modules/cjs/loader.js:735:32)
>     at Module._load (internal/modules/cjs/loader.js:648:12)
>     at Module._load (electron/js2c/asar.js:717:26)
>     at Function.Module._load (electron/js2c/asar.js:717:26)
>     at Module.require (internal/modules/cjs/loader.js:775:19)
>     at require (internal/modules/cjs/helpers.js:68:18)
>     at Function.Reporter.loadReporter (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\lib\reporter.js:386:16)
>     at Project.watchSettingsAndStartWebsockets (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\lib\project.js:310:18)
>     at C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\lib\project.js:142:16
>     at tryCatcher (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:544:35)
>     at Promise._settlePromise (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
>     at Promise._settlePromise0 (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
>     at Promise._settlePromises (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
>     at Promise._fulfill (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
>     at PromiseArray._resolve (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:127:19)
>     at PromiseArray._promiseFulfilled (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:145:14)
>     at PromiseArray._iterate (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:115:31)
>     at PromiseArray.init [as _init] (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:79:10)
>     at Promise._settlePromise (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:601:21)
>     at Promise._settlePromise0 (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
>     at Promise._settlePromises (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
>     at _drainQueueStep (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
>     at _drainQueue (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
>     at Async._drainQueues (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\apopi\AppData\Local\Cypress\Cache\3.8.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
>     at processImmediate (internal/timers.js:439:21)
> 
> 
> Learn more at https://on.cypress.io/reporters
> 
> `_

**Comment by Ebazhanov** [comment]
can you also please share what is inside your :
- `cypress/plugins/index.js` file
- `cypress/support/index.js` file
- and how you add this plugin inside your `package.json`

**Comment by Shelex** [comment]
@archital Thank you for opening issue with detailed info!
Actually you don't need to include this plugin as reporter in your cypress.json, please just follow steps in readme.

**Comment by Shelex** [comment]
In https://github.com/Shelex/cypress-allure-plugin/commit/c766ddb25c8141f0e012ca9edf0e00d443074f10 have mentioned that there is no need to install this plugin as reporter + option to customize allure-results output folder. README is updated to reflect latest changes.

**Comment by archital** [comment]
> In [c766ddb](https://github.com/Shelex/cypress-allure-plugin/commit/c766ddb25c8141f0e012ca9edf0e00d443074f10) have mentioned that there is no need to install this plugin as reporter + option to customize allure-results output folder. README is updated to reflect latest changes.

Many thanks! Once I removed my old reporter:
```
 "reporter": "mocha-allure-reporter",
  "reporterOptions": {
    "targetDir": "allure"
  }
``` new one with public Allure's API starts working!
