### ISSUE TITLE
'Cannot read property 'addAttachment' of null' error if the test failed in the 'before' function

### ISSUE THREAD

**Issue by Deop** [Shelex/cypress-allure-plugin#32]
**Describe the bug**
If the test failed in the 'before' function, prior to any test body, the 'Cannot read property 'addAttachment' of null' error happen and is shown in cypress, instead of an actuall error that happened.
Apparently, it seems like the error is caused by the fact that this.reporter.currentTest is null. Please check screenshot for the detailed error.

**To Reproduce**
Setup cypress with cypres-allure-lugin
1. Add a simple assert that would fail into the before function to the test (e.g. - expect(1).to.eq(2);)
2. Run the test
3. See error

**Expected behavior**
Errors in before function are handled properly, not causing allure-plugin to fail and create there own errors.

**Environment (please complete the following information):**
- Cypress version:                                5.6.0
- OS:                                                     Windows

** Developer Tools Console Output **
Cannot read property 'addAttachment' of null
Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: Sample Describe

**Additional context**
![image](https://user-images.githubusercontent.com/7953144/99537752-bd32b080-29b4-11eb-82b1-77914eec54db.png)

**Comment by Shelex** [comment]
@Deop Hi! Thank you for opening an issue.

Should be resolved in v1.8.5, could you please check if it works on your end?

**Comment by Deop** [comment]
@Shelex Hi! Yeah, it looks good now. Thanks for the quick fix
