### ISSUE TITLE
cy.allure().story('A-Story') is not shown in generated html report

### ISSUE THREAD

**Issue by Karnikel** [Shelex/cypress-allure-plugin#35]
**Describe the bug**
If I use the API to add some test informations to the test report with ``cy.allure().story('A-Story')``, the mentioned information is not visible in test report html.

**To Reproduce**
1. Write a test with the following line in it: ``cy.allure().story('A-Story').issue('An-Issue', 'An-Issue_URL')`` 
    e.g.:
    ```
    describe('test suite', () => {
      it('test case', () => {
        cy.allure().story('A-Story').issue('An-Issue', 'An-Issue_URL')
        cy.visit('www.google.de');
      });
    });
    ```
2. Generate html report
--> The issue link ``An-Issue`` is visible on html report --> OK
--> The stroy link ``A-story`` is NOT visible on html report --> NOK
Hint: Didn't tested all available tags. Maybe the issue occurs also with other tags.

**Expected behavior**
Both informations (issue and story link) are visible in html report

**Environment:**
- Cypress version:                                6.0.1
- Cypress-allure-plugin version:           1.8.5
- OS:                                                     Windows

**Comment by Shelex** [comment]
@Karnikel Hello. Have done a lot of fixes which should solve such issue. Could you please check v.1.10.1?

**Comment by Shelex** [comment]
@Karnikel Also, the concept of epic -> feature -> story is just for behaviours plugin the same as specs are grouped in suites tab:
"Suites": parentSuite, suite, subSuite
"Behaviors": epic, feature, story

**Comment by Karnikel** [comment]
OK...thanks for the answer.
Could my bug ticket become a feature request? ;)

**Comment by Shelex** [comment]
> OK...thanks for the answer.
> Could my bug ticket become a feature request? ;)

Could you please specify what exactly could be improved in terms of this plugin? Because in case you want these labels to be visible I guess allure-framework itself would be a place for it.

**Comment by Karnikel** [comment]
Sure...I think it would be great if I can see also a story link next to the issue link at the test execution trace if I write the following line:
```cy.allure().story('A-Story').issue('An-Issue', 'An-Issue_URL')```
Don't know if it's just a small and simple implementation (addition) to you plugin.

**Comment by Shelex** [comment]
> Sure...I think it would be great if I can see also a story link next to the issue link at the test execution trace if I write the following line:
> `cy.allure().story('A-Story').issue('An-Issue', 'An-Issue_URL')`
> Don't know if it's just a small and simple implementation (addition) to you plugin.

@Karnikel  maybe you need just `cy.allure().issue('An-Issue, 'Issue_ID').link('Story', 'https://link-to-story')`?

**Comment by Karnikel** [comment]
Ah, great! It's a good idea, thanks.
I think you can close this ticket.

**Comment by Shelex** [comment]
> Ah, great! It's a good idea, thanks.
> I think you can close this ticket.

Glad it helped!
