### ISSUE TITLE
possibility to generate junit xml format results

### ISSUE THREAD

**Issue by maga-polito** [Shelex/cypress-allure-plugin#36]
It is useful to have xml format junit results as well to publish results on azure devops platform

**Comment by Shelex** [comment]
> It is useful to have xml format junit results as well to publish results on azure devops platform

Hello @maga-polito ! Thank you for opening an issue.
I guess for producing junit format you can use inbuilt [cypress junit reporter](https://docs.cypress.io/guides/tooling/reporters.html#Custom-reporter). This plugin is just for Allure reporter and is not depending on others.
