### ISSUE TITLE
Integrate cypress-allure-plugin with Cypress 5+ Retry functionality

### ISSUE THREAD

**Issue by markroche32** [Shelex/cypress-allure-plugin#39]
**Is your feature request related to a problem? Please describe.**
Integrate cypress-allure-plugin with Cypress 5+ Retry functionality

**Describe the solution you'd like**
Cypress 5+ allows for Retry test when it fails to the number of times, n 

"retries": {
    "runMode": 2,
    "openMode": 2
  },

- discard previous passed and failed screenshot attempts from attachments in report

**Additional context**
Currently cypress-allure-plugin with Cypress 5+ Retry functionality :

- previous passed and failed screenshot attempts appear in attachments in report

**Comment by Shelex** [comment]
@markroche32 Have published v.2.0.3 where you can find cypress env configuration option `allureOmitPreviousAttemptScreenshots`. Just set it to `true` and screenshots from previous attempts will be discarded.
