### ISSUE TITLE
please add label->framework

### ISSUE THREAD

**Issue by kristina-hager** [Shelex/cypress-allure-plugin#42]
Hi there!
My team is looking into using allure reports more broadly - across many test platforms.
The allure report for some (particularly officially supported) frameworks includes the framework name, as in:

```
  "labels": [
    {
      "name": "framework",
      "value": "junit-platform"
    },
...
```

It seems this info is hardcoded into the plugin as in this LOC:
https://github.com/allure-framework/allure-java/blob/5365fddefb684ca4d4abd6b43c5ec7b10f2215d3/allure-junit-platform/src/main/java/io/qameta/allure/junitplatform/AllureJunitPlatform.java#L376

As in, if you're using this code you must be using junit (and they populate language:java as well). :-)

Would you be open to including a framework -> cypress label in this repo?

I'm open to providing a PR myself or from my team, but I just wanted to float the idea to you first.

**Comment by kristina-hager** [comment]
Ah, yes, my apologies for saying 'every test'. I meant 'every test suite'.

The solution https://github.com/mmisty/jest-allure2-adapter#custrom-jasmine-reporter would certainly work to add arbitrary labels/etc to a report coming from a test suite. If the label was very specific to that test suite, this would be very reasonable. Also I might add, this approach will be very complex to apply to thousands of test suites across hundreds of products.

However, framework:jest is not an arbitrary label.
This would be parity with what other allure reporters consistently add without any additional configuration required from the test code. I will include both an example from both pytest and junit5 below. There are actually considerably more fields included by default, although my focus for now is on "framework" (language would be nice too though it's kind of implied!).

Again, I am glad to contribute code to this project, if you are open to contributors. 

java example of the labels:
```
"labels": [
    {
      "name": "host",
      "value": "IT-HOLA-02"
    },
    {
      "name": "thread",
      "value": "59625@IT-HOLA-02.Test worker(12)"
    },
    {
      "name": "framework",
      "value": "junit-platform"
    },
    {
      "name": "language",
      "value": "java"
    },
    {
      "name": "package",
      "value": "com.foo.test.BarJUnit5Test"
    },
    {
      "name": "testClass",
      "value": "com.foo.test.BarJUnit5Test"
    },
    {
      "name": "testMethod",
      "value": "testValueSourceWithSomeFailed"
    },
    {
      "name": "suite",
      "value": "com.foo.test.BarJUnit5Test"
    }
  ],
```

python:
```
  "labels": [
    {
      "name": "parentSuite",
      "value": "tests"
    },
    {
      "name": "suite",
      "value": "test_example"
    },
    {
      "name": "subSuite",
      "value": "TestCase"
    },
    {
      "name": "host",
      "value": "IT-HOLA-9"
    },
    {
      "name": "thread",
      "value": "17359-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "tests.test_example"
    }
  ],
```

**Comment by Shelex** [comment]
Hi @kristina-hager and thank you for opening feature request.
Actually, Allure framework used it previously for tracking user events in google analytics - [GaPlugin.java](https://github.com/allure-framework/allure2/blob/master/allure-generator/src/main/java/io/qameta/allure/ga/GaPlugin.java#L84) to investigate how people are using Allure with specific framework or language. In case label is added to test it will not be displayed anywhere in report.
So I would advise to use parameter for defining framework: `cy.allure().parameter("framework", "Cypress")` in beforeEach hook, or with `cy.allure().writeEnvironmentInfo({ "framework": "Cypress" })` for entire run.

Hope it helps.

**Comment by kristina-hager** [comment]
Interesting. I was not aware until this that allure was using google analytics. I think this page describes their usage well: https://github.com/allure-framework/allure2/blob/master/Analytics.md

My interest in this topic is similar. I work at a very large company and we need to do an analysis of what languages/frameworks our tests are using. For some context, we have many hundreds of repositories with many tests in each.
The solution you suggest would involve touching each repository that is using cypress testing. This would be a large effort and add repetitive code to each repository. Also, each new repository would need to do this.

Furthermore, showing language/framework in the labels section would be parity with other allure plugins. Also, another user contributed jest plugin [made the same change](https://github.com/mmisty/jest-allure2-adapter/issues/1). I will include an example from python and java below of the labels field, default behavior only, for some context.

Again, I'd be glad to contribute a PR make this change, if you are open to the contribution.

java example of the labels:
```
"labels": [
    {
      "name": "host",
      "value": "IT-HOLA-02"
    },
    {
      "name": "thread",
      "value": "59625@IT-HOLA-02.Test worker(12)"
    },
    {
      "name": "framework",
      "value": "junit-platform"
    },
    {
      "name": "language",
      "value": "java"
    },
    {
      "name": "package",
      "value": "com.foo.test.BarJUnit5Test"
    },
    {
      "name": "testClass",
      "value": "com.foo.test.BarJUnit5Test"
    },
    {
      "name": "testMethod",
      "value": "testValueSourceWithSomeFailed"
    },
    {
      "name": "suite",
      "value": "com.foo.test.BarJUnit5Test"
    }
  ],
```

python:
```
  "labels": [
    {
      "name": "parentSuite",
      "value": "tests"
    },
    {
      "name": "suite",
      "value": "test_example"
    },
    {
      "name": "subSuite",
      "value": "TestCase"
    },
    {
      "name": "host",
      "value": "IT-HOLA-9"
    },
    {
      "name": "thread",
      "value": "17359-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "tests.test_example"
    }
  ],
```

**Comment by Shelex** [comment]
@kristina-hager Thank you for your message.
Unfortunately, this labels like "framework" and "language" are not shown actually in your report anywhere. It will not address your issue of analysis what framework and language is used at all.
To check that, please try adding to some of your test results labels in `allure-results` folder:
```json
 {
      "name": "framework",
      "value": "cypress"
    },
    {
      "name": "language",
      "value": "javascript"
    }
```
and generate a report - it will have no effect.
So I would advise several options:
 - `cy.allure().writeEnvironmentInfo({ "framework": "Cypress" })`
 - add file `environment.properties` to allure-results before generating report
 ```txt
 framework=Cypress
 language=javascript
 ```
  - add such file as step before generating report with bash command:
  `touch allure-results/environment.properties &&  echo -e "framework=Cypress\nlanguage=javascript" > allure-results/environment.properties`
  - use `cy.allure().tag('Cypress')` in beforeach hook to display it as a tag, but env info would be more clear.

**Comment by kristina-hager** [comment]
> Unfortunately, this labels like "framework" and "language" are not shown actually in your report anywhere.

Yes, I'm aware this info doesn't show up in the allure report. This is not what I'm seeking.

However, the info IS present in the output files from allure (for most test frameworks anyway). That means the info can be extracted. It is this extracted info I would use.

I do understand the approaches you are suggesting for adding them to cypress tests. However, those approaches simply won't scale.

In the other test framework plugins for allure, the framework/language info is simply hardcoded. As an example, [here](https://github.com/mmisty/jest-allure2-adapter/commit/0fc7f2c3de4548682360fb03b30e8c12ae92ed44) is where the jest-allure2-adapter lib recently made the requested change.

**Comment by Shelex** [comment]
@kristina-hager ok, got your point. 
I think parsing framework or language labels from allure-results in order to analyse reports from various projects is a very narrow use case to be implemented in this plugin. 
Only option I see for now - add some configuration option disabled by default, which would add such labels.

**Comment by kristina-hager** [comment]
@Shelex  are you now open to me or my team submitting a PR to add the framework and language labels? If so, can this issue be reopened as it would be then in-progress?

**Comment by Shelex** [comment]
@kristina-hager in v2.3.0 added configuration env variable `allureAddAnalyticLabels` which can enable labels `framework` and `language`.
