### ISSUE TITLE
Consider supporting tmsPostfix

### ISSUE THREAD

**Issue by szgabsz91** [Shelex/cypress-allure-plugin#43]
**Is your feature request related to a problem? Please describe.**
In case of SpiraTeam, the URLs end in `.aspx` but this use case is not currently supported by the current configuration.

**Describe the solution you'd like**
The config could include a new optional `tmsPostfix` property that could be appended to the final URL.

**Additional context**
-

**Comment by Shelex** [comment]
Hey @szgabsz91 
Thank you for opening an issue for feature request.

It is addressed in v.2.1.0
You can now set your `tmsPrefix` with `*` character, so it will act as a pattern:
```json
{
    "env": {
        "tmsPrefix": "https://spira-team.com/test-cases/*.aspx"
    }
}

```

**Comment by szgabsz91** [comment]
Oh, thanks for the help, I haven't see this option yet.

However, this only works with native Cypress and not with the Cucumber preprocessor, because the `AllureReporter` class only concats the prefix and the URL and does not handle the asterisk character the same way as in `commands.js`.

I'd create a new PR to fix this issue later this day.

**Comment by Shelex** [comment]
@szgabsz91 Thank you for clarifying. Addressed in v.2.2.1

**Comment by szgabsz91** [comment]
You're quick! :) Thanks for the fix, I'll test it later, but it seems to be OK.

Thank you for your help!
