### ISSUE TITLE
the report shows the passed test steps as fallen

### ISSUE THREAD

**Issue by jbelyaeva** [Shelex/cypress-allure-plugin#45]
** Description of the error **
the results of the steps taken are displayed incorrectly when "allureLogCypress": false

** Playback **

1.set variable "allureLogCypress": true
2.run the test script:

describe ('example ->', function () {

    it ('test # 1', () => {
        cy.allure (). step ("visit 1", false);
        cy.visit ("http://example.com");

        cy.allure (). step ("visit 2", false);
        cy.visit ("http://example.com");

        cy.allure (). step ("visit 3", false);
        cy.visit ("http://example555.com");
    });
    });

3. [view the report (the display of steps is correct).](https://cloud.mail.ru/public/EMCw%2FFRRSMo9qs)

4.set variable "allureLogCypress": false
5. run the test script:

describe ('example ->', function () {

    it ('test # 1', () => {
        cy.allure (). step ("visit 1", false);
        cy.visit ("http://example.com");

        cy.allure (). step ("visit 2", false);
        cy.visit ("http://example.com");

        cy.allure (). step ("visit 3", false);
        cy.visit ("http://example555.com");
    });
    });

6.[ view the report (all steps are displayed as fallen)](https://cloud.mail.ru/public/pfKS%2FWwh2X2zBa).

** Expected Behavior **
The report is expected to display successfully completed steps in green, dropped in red.

** Environment (please fill in the following information): **
- Cypress version: 6.0.3
- OS: Windows 10
- cypress-allure-plugin v.2.2.0

**Comment by jbelyaeva** [comment]
**Update:** 
there are problems when using before, beforeEach, after, afterEach:

1.  using step:
 
   ` describe('example ->', function () {

    before(() => {
        cy.allure().step("visit before", false);
        cy.visit("http://example.com");
    });

    beforeEach(() => {
        cy.allure().step("visit beforeEach", false);
        cy.visit("http://example.com");
    });

    afterEach(() => {
        cy.allure().step("visit afterEach", false);
        cy.visit("http://example.com");
    });

    after(() => {
        cy.allure().step("visit after", false);
        cy.visit("http://example.com");
    });

    it('test #1', () => {
        cy.allure().step("visit 1", false);
        cy.visit("http://example.com");

        cy.allure().step("visit 2", false);
        cy.visit("http://example.com");

        cy.allure().step("visit 3", false);
        cy.visit("http://example555.com");
    });
    });`

provided "allureLogCypress": true
[we get a correct report](https://cloud.mail.ru/public/jtgR%2Ft9NQ4SPr8) 

provided "allureLogCypress": false
[we get an incorrect report](https://cloud.mail.ru/public/j3Wj%2FZmwzZzWTB)

2.  using startStep and endStep:

 `  describe('example ->', function () {

    before(() => {
        cy.allure().startStep("visit before");
        cy.visit("http://example.com");
        cy.allure().endStep();
    });

    beforeEach(() => {
        cy.allure().startStep("visit beforeEach");
        cy.visit("http://example.com");
        cy.allure().endStep();
    });

    afterEach(() => {
        cy.allure().startStep("visit afterEach");
        cy.visit("http://example.com");
        cy.allure().endStep();
    });

    after(() => {
        cy.allure().startStep("visit after");
        cy.visit("http://example.com");
        cy.allure().endStep();
    });

    it('test #1', () => {
        cy.allure().startStep("visit 1");
        cy.visit("http://example.com");
        cy.allure().endStep();

        cy.allure().startStep("visit 2");
        cy.visit("http://example.com");
        cy.allure().endStep();

        cy.allure().startStep("visit 3");
        cy.visit("http://example555.com");
        cy.allure().endStep();
    });
    });`

provided "allureLogCypress": true
[we get an incorrect report](https://cloud.mail.ru/public/cqbc%2FsFgiV4FjQ) 

provided "allureLogCypress": false
[we get an incorrect report](https://cloud.mail.ru/public/Jus8%2FahftmRLkw)

**Comment by Shelex** [comment]
@jbelyaeva Thank you for opening an issue and providing useful information.
It should be resolved in v.2.3.1
By the way, have also added alias command for `step("visit 1", false)`, it could be replaced with just `logStep("visit 1")`.

**Comment by jbelyaeva** [comment]
@Shelex, thanks for the work done, but there are still some problems in version 2.3.2:

**1.1. "allureLogCypress": true, using startStep endStep**  
![allureLogCypress=true_used_startStep endStep](https://user-images.githubusercontent.com/59063644/108182257-debd4880-7119-11eb-9d72-cbfbbf87c410.jpg)
**1.2. "allureLogCypress": true, using step** 
![allureLogCypress=true_used_step](https://user-images.githubusercontent.com/59063644/108182347-f72d6300-7119-11eb-9fb0-7b5f389fa399.jpg)
**1.3. "allureLogCypress": true, using logStep** 
![allureLogCypress=true_used_logStep](https://user-images.githubusercontent.com/59063644/108182370-fd234400-7119-11eb-95ad-417b0dbedc61.jpg)

**2.1. "allureLogCypress": false, using startStep endStep**
![allureLogCypress=false_used_startStep endStep](https://user-images.githubusercontent.com/59063644/108182504-2348e400-711a-11eb-9e4d-448b87a561e1.jpg)
**2.2. "allureLogCypress": false, using step**
![allureLogCypress=false_used_step](https://user-images.githubusercontent.com/59063644/108182544-2e037900-711a-11eb-948d-5aea8b36a71a.jpg)
**2.3. "allureLogCypress": false, using logStep**
![allureLogCypress=false_used_logStep](https://user-images.githubusercontent.com/59063644/108182575-35c31d80-711a-11eb-801a-c3e2895edee4.jpg)

**Comment by Shelex** [comment]
@jbelyaeva thank you for perfect testing of this feature!
Addressed in v.2.3.4

**Comment by jbelyaeva** [comment]
@Shelex now everything works fine. Thank you so much!
