### ISSUE TITLE
Execution get stuck when using context.Skip() with allure

### ISSUE THREAD

**Issue by suniljaiswal01** [Shelex/cypress-allure-plugin#51]
**Describe the bug**
When Adding context.skip to spec file and keeping allure=true in the config, the execution is getting stuck and not getting terminate. Below is the screenshot for the same:
![image](https://user-images.githubusercontent.com/45997477/108160278-cbf14680-710e-11eb-9540-bcb02047c01c.png)

**To Reproduce**
1. Clone the repo  https://github.com/Shelex/cypress-allure-plugin-example
2. Update contextto context.skip in action.spec.js file
3. Run the command "yarn cy:run"

**Expected behavior**
Testcase should get skip and execution should be completed

**Environment (please complete the following information):**
- Cypress version:                                6.2.0
- OS:                                                     Windows 10

** Developer Tools Console Output **

**Additional context**

**Comment by suniljaiswal01** [comment]
If we add allure=false in the command and then run, then it is skipping the test properly and execution is getting completed

**Comment by Shelex** [comment]
@suniljaiswal01 
Fixed in v2.3.4
However, there is no possibility to write allure results for skipped suite, as cypress cannot execute cy.task in such case.
