### ISSUE TITLE
@link annotation in gherkin file doesn't work

### ISSUE THREAD

**Issue by bebop23** [Shelex/cypress-allure-plugin#64]
**Describe the bug**
When trying to add a @link annotation to any scenario, it shows up as a Tag instead.

**To Reproduce**
1. In the `cypress/integration/cucumber/news/Google.feature` add:
```gherkin
    @link("https://google.com","google")
    Scenario: Opening a Google network page
        Given I open Google page
        Then I see "Google" in the title
```
2. Then run the `yarn cy:cucumber:run`, followed by `yarn allure:report`, and finally `allure open`
3. You will see that `link` shows up as a Tag instead of a Link.

<img width="624" alt="Screen Shot 2021-04-07 at 11 34 45 PM" src="https://user-images.githubusercontent.com/1031676/113969094-f6e84480-97f9-11eb-9a4c-1640390f4bd6.png">

**Expected behavior**
One would expect to see it under the **Links** section as a link entry.

**Environment (please complete the following information):**
- Cypress version:                               6.2.0
- OS:                                                     Mac

**Comment by Shelex** [comment]
@bebop23 Hi. Have published v2.5.0 where this should be addressed.

**Comment by bebop23** [comment]
Awesome @Shelex!  Thanks for quickly resolving this!

**Comment by Shelex** [comment]
@bebop23 Glad it helped. Feel free to star this repo :D

**Comment by bebop23** [comment]
@Shelex you got it ;)
