### ISSUE TITLE
Possibility to add video for passed tests

### ISSUE THREAD

**Issue by ulianek** [Shelex/cypress-allure-plugin#68]
Hi,

My client requires to add video to each test, both passed and failed. Currently, I see that there is a possibility to attach videos to failed tests, but I don't know how to attach movies to those, which ended successfully.  

I've tried to do this in test:after:run and also in afterEach, but it seems it doesn't work (Maybe because video is generated later and not exists at the moment when I execute that command?) Or maybe there is a workaround and I didn't find a solution. It would be perfect to add this feature, or advise me, is there any workaround?

```
Cypress.on('test:after:run', (err, runnable) => {
    cy.allure().fileAttachment(
        `${Cypress.spec.name}.mp4`,
        path.join(
            Cypress.config().videosFolder,
            `${Cypress.spec.name}.mp4`
        ),
        'video/mp4'
    );
})
```

Best regards

**Comment by Shelex** [comment]
Hi @ulianek . Resolved in v2.7.0 with new configuration option `allureAddVideoOnPass`. If set to `true` will attach paths of video files to allure report.
