### ISSUE TITLE
tests cannot be marked as @Flaky

### ISSUE THREAD

**Issue by maga-polito** [Shelex/cypress-allure-plugin#69]
According to allure framework it should be possible to mark some tests as flaky by adding corresponding tag @Flaky, however it seems like it is not supported by plugin

**Comment by Shelex** [comment]
@maga-polito Hi. Thank you for mentioning this topic. While working on this plugin I have also found that tag, however, even it is mentioned in some of java integration, it was working (as far as I understood) with Allure v1 only (where results are written as xml files). In Allure v2 this tag is ignored completely and is set automatically when report is generated on history basis - when failed test becomes passed you will see small bomb icon near title.
So, unfortunately, at this moment there is no option to bypass that without a fix inside Allure - https://github.com/allure-framework/allure2/pull/1135

**Comment by maga-polito** [comment]
@Shelex you're right, I could verify that based on history framework marks automatically flaky tests, so there’s no point on adding it manually ..thanks
