### ISSUE TITLE
Question: are there any options to overwrite displayName in runtime?

### ISSUE THREAD

**Issue by dkorobtsov** [Shelex/cypress-allure-plugin#70]
**Is your feature request related to a problem? Please describe.**

Use case is following: sometimes, when running parameterised tests there is a need to overwrite test name after test has already started. Wonder if it can be achieved with this plugin? 🤔  Any plans to add something like `allure.displayName("Readable Name")`
?

**Comment by Shelex** [comment]
Hi @dkorobtsov, thank you for opening an issue.

That is doable, however would be too tricky to do during test run, so I added that option when results are saved to fs.
In 2.6.0 you can add `allure().testName('Rradable name')` and in allure results test will have this name.
