### ISSUE TITLE
Allure Plugin not working when used with "Cypress-grep" plugin

### ISSUE THREAD

**Issue by suniljaiswal01** [Shelex/cypress-allure-plugin#72]
**Describe the bug**
When we implement the changes required for "Cypress-grep " plugin, and then try to run the testcase, allure report is not getting generated

**To Reproduce**
1. Clone the repo https://github.com/Shelex/cypress-allure-plugin-example
2. Implement the changes mentioned in the link(https://github.com/bahmutov/cypress-grep)
3. update 'it' block in action.spec.js file as `it('.focus() - focus on a DOM element',{tags:'smoke'}, () => {`
4. add grepTags='smoke' in cy:run script in package.json file
4. Execute cy:run script from package.json file

**Expected behavior**
After the end of execution , allure result folder should get generated.

**Environment (please complete the following information):**
- Cypress version:                                6.2.0
- OS:                                                     Windows

** Developer Tools Console Output **

**Additional context**

**Comment by Shelex** [comment]
Hi @suniljaiswal01,
thank you for opening an issue.

I think problem is that plugins are using same Cypress functionality for configuration - [Cypress environment variables](https://docs.cypress.io/guides/guides/environment-variables#Option-4-env).
In case several `--env` entries are passed it may override it and use just last env argument (in our case - grepTags)
Solution would be to pass env variables as one argument, like:
```bash
cypress run --env allure=true,grepTags='smoke'
```

I will update documentation as this overriding may confuse a lot of people.

**Comment by suniljaiswal01** [comment]
Hi @Shelex , thank you for the workaround, after passing the argument in the env variable, the grep is doing the filter properly, however it is only filtering the 1st spec file having the tag, i have multiple files having the same tag, but it is running only for the 1st matched files and ignoring the other spec files
