### ISSUE TITLE
Execution is stuck when a test is skipped and afterEach function is defined

### ISSUE THREAD

**Issue by haipinggong** [Shelex/cypress-allure-plugin#77]
**Describe the bug**
The execution of Cypress is stuck if a test is skipped and there is an afterEach function defined in the spec.js file.

**To Reproduce**
1. Add a test as in a spec.js file: 
    it('skip', function () {
        this.skip()
    });
2. Add an afterEach function in the same spec.js file
    afterEach(function () {
        cy.log('This is after each test')
    })
3. Run that spec.js file with --env allure=true:
npx cypress open --env allure=true
4.  Cypress execution is stuck after reaching that test case.

**Expected behavior**
The cypress execution should not be stuck. The test run can go on to the next test case.

**Environment (please complete the following information):**
- Cypress version:                                7.5.0
- OS:                                                     Windows (10):

** Developer Tools Console Output **

Uncaught TypeError: Cannot read property 'startStep' of null
    at AllureReporter.startHook (AllureReporter.js:364)
    at Runner.eval (index.js:115)

**Additional context**
If the afterEach function is empty like:
    afterEach(function () {}), the test execution is not stuck.

Please refer to the attached spec.js file that I modified in https://github.com/Shelex/cypress-allure-plugin-example
The js file cannot be uploaded so I renamed it to txt file.
[steps.spec.txt](https://github.com/Shelex/cypress-allure-plugin/files/6652896/steps.spec.txt)

**Comment by Shelex** [comment]
Hi @haipinggong 
Have provided a fix in v2.8.2 where it should be resolved.

Could you please check on your case?

**Comment by haipinggong** [comment]
@Shelex , thanks. I have upgraded to v2.8.2 and I think it is fixed.
