### ISSUE TITLE
Automatically create Allure steps out of custom commands

### ISSUE THREAD

**Issue by Yethal** [Shelex/cypress-allure-plugin#8]
**Is your feature request related to a problem? Please describe.**
In Java-based frameworks, Allure automatically creates steps out of test methods and sets the step name to method name. Test engineer can optionally add @Step annotation to the method to add a readable step name to the report. In Cypress however all instructions (and XHRs) are treated as separate steps regardless of whether they're a part of custom command or not. The only way to transform them into a proper Allure step is to manually add cy.allure().step('Step name') chainer to every custom command (which is tedious)

**Describe the solution you'd like**
Custom commands are automatically turned into steps with the step name set to command name and command arguments listed after the step name, e.g

```
Cypress.Commands.add('Do something', (variable) => {
//step content here
});
```
Would create Allure step named ```Do something, variable```
**Additional context**

**Comment by Shelex** [comment]
@Yethal Just released v1.7.0 where such feature is implemented. Could you please check it for your specific case?
