### ISSUE TITLE
Parameter for prefix/allias in name of test reports

### ISSUE THREAD

**Issue by OskarSnuszka** [Shelex/cypress-allure-plugin#84]
**Is your feature request related to a problem? Please describe.**
I want to merge allure results from two test runs. The only difference between those test run are browser, because of that test names in reports have the same name, and after  **allure serve** command (command to merge reports), I'll have only one group of tests in allure report because of the same name.

**Describe the solution you'd like**
Prefix or alias defined in config *JSON file would be perfect. Like in below example:

![2021-07-05_12h42_38](https://user-images.githubusercontent.com/78599192/124459530-8320ee00-dd8e-11eb-8e33-df7037db41e8.png)
![2021-07-05_12h44_48](https://user-images.githubusercontent.com/78599192/124459801-d8f59600-dd8e-11eb-8fc6-5f1373dc22a1.png)

And then I'll run my automation with this parameter change to have any ability to use allure serve

**Comment by Shelex** [comment]
Hi @OskarSnuszka 
Thank you for opening an issue.

Plugin already has command `cy.allure().testName('new test name')`, and I thought to suggest you reusing it for your case. However found an issue that historyId (which is used to separate tests) is based on md5 hash from test name, and is not recalculated in case test title was updated. So released v.2.8.4 to address this issue and now your issue could be resolved by adding beforeEach hook for your tests:
```js
beforeEach(() => {
        cy.allure().testName(
            `${Cypress.browser.name} - ${cy.state().test.title}`
        );
    });
```

Could you please try to upgrade to latest version, and check if it works for your case?

**Comment by OskarSnuszka** [comment]
thank you for yours answer - I will try it

**Comment by OskarSnuszka** [comment]
![2021-07-08_09h10_40](https://user-images.githubusercontent.com/78599192/124878423-63770900-dfcc-11eb-9d7f-aca38630b3c7.png)

@Shelex it's working by your way of implementation - thanks for your time

Issue can be closed
