### ISSUE TITLE
I want to group results based on paths, Is there any way for that 

### ISSUE THREAD

**Issue by sanjayupasi** [Shelex/cypress-allure-plugin#87]
we have structure like,

 1. **/folder1/**/.*.spec.js,
 2. **/folder2/*/*/.*.spec.js,
 3. **/folder3/*/*/*/.*.spec.js,

I wanted results to be grouped under toggles like...
folder1-
    |_ spec1
           |_ testcase1   
           |_ testcase2...

**Comment by Shelex** [comment]
Hi @sanjayupasi 
Thank you for opening an issue. 

It is available by setting up parentSuite for each test based on folder name, so let's take an example:
```
cypress
       - integration
                  - folder1
                  - folder2
```

Then in cypress/support/index.js I add a hook:
```
beforeEach(() => {
    const { spec } = Cypress;
    cy.allure().label('parentSuite', spec.name.split('/').shift());
});
```
This will set folder1 or folder2 as parentSuite for my tests:
<img width="800" alt="Allure Report 2021-08-25 12-20-45" src="https://user-images.githubusercontent.com/11396724/130764568-42c7860b-f325-4e4d-9294-4a9759a30e0e.png">

Hope this would help.

**Comment by sanjayupasi** [comment]
it really helped @Shelex thank you....!!!!
