### ISSUE TITLE
"before each" hook is considered as a step in allure report 

### ISSUE THREAD

**Issue by kizrazh** [Shelex/cypress-allure-plugin#89]
**Describe the bug**
"before each" hook is considered as a step in allure report 

**To Reproduce**

Run script with beforeEach() hook: 

describe('Authorization ', () => {

beforeEach(() => {
        const allure = Cypress.Allure.reporter.getInterface()
        allure.step('Перейти по ссылке http://')
})
//test cases
})

**Expected behavior**
there is no step "before each" in allure report, first step should be 'Перейти по ссылке http://'

**Environment (please complete the following information):**
- Cypress version:                                8.0.3
- OS:                                                     Windows:
- Allure plugin version                         2.14 

![12-16-16](https://user-images.githubusercontent.com/91251711/134482715-ec58c7e1-2e3f-45a6-899f-2b9844a9ab18.png)

**Comment by Shelex** [comment]
Hi @kizrazh 
That is intentional implementation by-design.
Technically, beforeEach and afterEach hooks are parts of cypress tests, so in order to enable adding attachments, labels, etc in hooks for current test it was made as a part of test itself.

In case problem is just with logging - that is separate thing, you can completely disable it by passing `allureLogCypress=false` cypress env variable.

**Comment by kizrazh** [comment]
Hi @Shelex! we've tried to disable it, but it didn't work, and hook step still present. We tried  like this: 
npx cypress run --env allureLogCypress=false --spec **/authorization.js
and in cypress.json

**Comment by Shelex** [comment]
Yep, reproduces for me, will be fixed in next version.

**Comment by kizrazh** [comment]
thanks!

**Comment by Shelex** [comment]
@kizrazh should be resolved in v2.15.0. Could you please check it on your side?

**Comment by Shelex** [comment]
Also, maybe it would help that in v2.16.0 each hooks step title could be configured with custom name:
```js
beforeEach('someCustomName', () => {
//...
});
```

**Comment by kizrazh** [comment]
thanks. it helped
