### ISSUE TITLE
Empty steps from "before/after" appear in reports when test runned with "allureLogCypress": false

### ISSUE THREAD

**Issue by kizrazh** [Shelex/cypress-allure-plugin#90]
We tried to disable "before/after " hooks logs so these steps are not displayed in allure report, but now we have Unknown steps instead 

Run script with before()/after() hooks:

describe('Authorization ', () => {

before(() => {
    })
    after(() => {
    })
describe('Авторизация пользователя', () => {

//test cases...

})

Expected behavior
there is no "before/after " or "Unknown" steps  in allure report 

Environment:

Cypress version: 8.4.1
OS: Windows
Allure plugin version 16 
AllureEE

![1](https://user-images.githubusercontent.com/91251711/134644829-d92b37df-1f2a-4d34-be95-c3ca11e8f573.jpg)
![2](https://user-images.githubusercontent.com/91251711/134644833-92826b7f-625f-45da-9c0e-1a28316e8244.jpg)

**Comment by Shelex** [comment]
Hi @kizrazh 
Thank you for opening an issue. 
Should be resolved in 2.16.1

**Comment by kizrazh** [comment]
thanks!
