### ISSUE TITLE
Plugin does not load screenshots to report

### ISSUE THREAD

**Issue by rkhomi** [Shelex/cypress-allure-plugin#92]
Plugin does not load screenshots to report, does not matter whether it's test body or any hooks
 On the other side there is no issue with video
 
 
![telegram-cloud-photo-size-2-5364182362365212218-x](https://user-images.githubusercontent.com/85738556/134694364-ae157766-099c-47df-9deb-06b3c8acc62e.jpg)

![telegram-cloud-photo-size-2-5364182362365212219-x](https://user-images.githubusercontent.com/85738556/134694394-956d5875-205b-43ad-be9b-a9dfe606c491.jpg)

**Comment by romankhomitskyi** [comment]
Issue could be closed as I couldn't provide steps to reproduce
