### ISSUE TITLE
Screenshot from cy.screenshot() generated to allure-result got error

### ISSUE THREAD

**Issue by lct005** [Shelex/cypress-allure-plugin#96]
**Describe the bug**
cy.screenshot() captured screenshot successfully but when generated to allure-result, it got error (with size of 1KB).
![image](https://user-images.githubusercontent.com/4641151/135018537-cb0edee4-5880-4534-a475-2190a63ab38f.png)

The API function cy.allure().fileAttachment() worked well with same screenshot taken from cy.screenshot() (from path 'cypress/screenshots/specs/fileImg.png')
![image](https://user-images.githubusercontent.com/4641151/135020388-79a005be-2491-441f-ad1f-fc0d2302a1fb.png)

**To Reproduce**
1. Use cy.screenshot() to capture and automatically attach to report
2. Use cy.screenshot() to capture, get screenshot path, and attach to report with cy.allure().fileAttachment()

**Expected behavior**
Screenshot taken from cy.screenshot() should be generated successfully to allure-result and able to see in report view

**Environment (please complete the following information):**
- Cypress version:                                8.4.1
- OS:                                                     Windows 10
- Cypress Allure Plugin version:           2.18.0
- Allure CLI:                                          2.13.8

**Comment by Shelex** [comment]
Hi @lct005 
Thank you for reporting this.

I could not exactly reproduce it, but anyway in v2.21.0 I have rework attachments and it should be much reliable as utilize cypress `after:spec` event which now provides real paths for screenshots. Could you please check it on your end?
