### ISSUE TITLE
Test that failed due to  Webpack Compilation Error is not attached to Allure report

### ISSUE THREAD

**Issue by romankhomitskyi** [Shelex/cypress-allure-plugin#98]
**Describe the bug**
There is no allureResults folder when test failed with that error
Cypress only generate video without screenshots
And that Fail is not visible in allure report

**To Reproduce**
1. Create test that has incorrect path to module (path to module has been updated)

**Expected behavior**
Failure is displayed in report

**Environment (please complete the following information):**
- Cypress version:   8.6.0                    
        
** Developer Tools Console Output **

Module not found: Error: Can't resolve.
Error: Webpack Compilation Error
Looked for and couldn't find the file at the following paths

**Comment by Shelex** [comment]
Hi @romankhomitskyi 
Unfortunately plugin cannot handle such error as it does not come from tests in browser, but happens in cypress node context during test code bundling to be sent to browser for execution. So technically as tests are not even started - plugin is not started also.
Such issues could be tracked on pre-commit hooks / CI level with eslint checks, as it does not relate to product under test, but to test code.
I recommend to look at [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import)
Hope this information would help.

**Comment by romankhomitskyi** [comment]
> Hi @romankhomitskyi Unfortunately plugin cannot handle such error as it does not come from tests in browser, but happens in cypress node context during test code bundling to be sent to browser for execution. So technically as tests are not even started - plugin is not started also. Such issues could be tracked on pre-commit hooks / CI level with eslint checks, as it does not relate to product under test, but to test code. I recommend to look at [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import) Hope this information would help.

Make sense, thank you

**Comment by Shelex** [comment]
Hi @romankhomitskyi 

I have reopened this issue, as it is implemented in v2.21.0 could you please check if it works fine for your case?

**Comment by romankhomitskyi** [comment]
HI @Shelex I have verified and can confirm it works well, thanks
