### ISSUE TITLE
Allure override previous succeeded it() with error from next before hook 

### ISSUE THREAD

**Issue by romankhomitskyi** [Shelex/cypress-allure-plugin#99]
**Describe the bug**
I hope this could be reproduced on others machines 
**To Reproduce**
Create spec file with the following structure and corresponding code to fail some of them
```
describe('Feature under test', () => {
	before(() => {
		// success actions 
	});

	describe('Create', () => {
		before(() => {
			// success actions 
		});

		it('should create', () => {
		// success actions 
		});
	});

	describe('Post', () => {
		before(() => {
		// success actions 
		});

		it('should post', () => {
			// success actions 
		});
	});

	describe('Clone', () => {
		before(() => {
			// failed actions 
		});

		it('should clone', () => {
		
		});
	});

	describe('Delete ', () => {
		before(() => {
		// actions that depends on previous Clone block so to say mutate data created in Clone block
		});

		it('should delete', () => {
		
		});
	});
});
```

**Expected behavior**
Each failed it() or before() block is displayed

**Environment (please complete the following information):**
- Cypress version:   8.6.0 
- OS: MAC
- Allure: 2.17.2 and 2.19.5                                          
![image](https://user-images.githubusercontent.com/57874507/141645465-935e31f2-5c1e-4479-bf2b-20d37a9823a5.png)

    
<img width="1168" alt="allure" src="https://user-images.githubusercontent.com/57874507/141645408-e00af304-d9a5-49d4-8e0e-13e582d9adc2.png">

**Comment by Shelex** [comment]
@romankhomitskyi I guess the root cause of a problem here are nested `describe` blocks, so events from mocha are not properly handled, as each `describe` creates new suite thus may lead to lost entities.
That requires more investigation how such nested structure could be handled properly.

**Comment by romankhomitskyi** [comment]
I also think that screenshots are not attached to report for this reason
